import Foundation
import Combine

enum AppLanguage: String, CaseIterable, Identifiable {
    case turkish = "tr"
    case english = "en"
    case german = "de"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .turkish: return "Türkçe"
        case .english: return "English"
        case .german: return "Deutsch"
        }
    }

    var localeIdentifier: String { rawValue }

    static func defaultFromDevice() -> AppLanguage {
        // Get the preferred language from the device
        let preferredLanguages = Locale.preferredLanguages
        let deviceLanguage = preferredLanguages.first?.prefix(2).lowercased() ?? "en"
        
        // Try to match with our supported languages
        if let language = AppLanguage(rawValue: deviceLanguage) {
            return language
        }
        
        // Fallback to English if device language is not supported
        return .english
    }
}

final class LocalizationManager: ObservableObject {
    static let shared = LocalizationManager()

    private let storageKey = "app_language"
    @Published var language: AppLanguage {
        didSet {
            UserDefaults.standard.set(language.rawValue, forKey: storageKey)
        }
    }

    private init() {
        // Always check device language first, unless user has explicitly set a preference
        if let stored = UserDefaults.standard.string(forKey: storageKey),
           let lang = AppLanguage(rawValue: stored) {
            // User has previously set a language preference
            language = lang
        } else {
            // First time launch - use device language (fallback to English)
            language = AppLanguage.defaultFromDevice()
        }
    }

    func translate(_ key: String, fallback: String? = nil, arguments: [CVarArg] = []) -> String {
        let template = translations[language]?[key] ?? fallback ?? key
        guard !arguments.isEmpty else { return template }
        let locale = Locale(identifier: language.localeIdentifier)
        return String(format: template, locale: locale, arguments: arguments)
    }

    private let translations: [AppLanguage: [String: String]] = [
        .turkish: [
            "TAB_FOCUS": "Odak",
            "TAB_MARKET": "Pazar",
            "TAB_BANK": "Banka",
            "TAB_WALLET": "Cüzdan",
            "TAB_FINANCE": "Finans",
            "TAB_HOME": "Ev",
            "MARKET_TOTAL_BALANCE": "Toplam Bakiye",
            "MARKET_OVERVIEW": "Piyasa değerinin güncel görünümü",
            "MARKET_COINS": "Coinler",
            "MARKET_SELL": "Sat",
            "MARKET_COIN_DESC_LEAF": "Odak coini: her seans sonrası küçük kazanç",
            "MARKET_COIN_DESC_ROOT": "Uzun vadeli yatırım: daha yüksek kazanç",
            "MARKET_COIN_DESC_BARK": "Dengeli coin: volatilitesi düşük",
            "MARKET_COIN_DESC_DEFAULT": "Özel coin",
            "SELL_COIN_SELECT": "Coin Seç",
            "SELL_COIN_SELECT_PLACEHOLDER": "Seçiniz",
            "SELL_COIN_AVAILABLE": "Mevcut: %@",
            "SELL_COIN_QUANTITY": "Miktar",
            "SELL_COIN_MARKET_VALUE": "Piyasa Değeri",
            "SELL_COIN_CLOSE": "Kapat",
            "SELL_COIN_SELL": "Sat",
            "SELL_COIN_ERROR_SELECT": "Coin seçiniz",
            "SELL_COIN_ERROR_QUANTITY": "Miktar sıfır olamaz",
            "SELL_COIN_ERROR_INSUFFICIENT": "Yetersiz coin",
            "BANK_ACCOUNT": "Banka Hesabı",
            "BANK_AVAILABLE": "Kullanılabilir",
            "WALLET_TITLE": "Cüzdan",
            "WALLET_ASSETS": "Varlıklar",
            "WALLET_EMPTY_ASSETS": "Henüz yatırım yapmadın",
            "WALLET_TRANSACTIONS": "Hareketler",
            "WALLET_EMPTY_TRANSACTIONS": "Henüz işlem yok",
            "WALLET_PASSIVE_TITLE": "Pasif kazanç birikimi",
            "WALLET_PASSIVE_RATE": "%d hız",
            "WALLET_SELL": "Sat",
            "WALLET_QUANTITY_SUFFIX": "%@ adet",
            "WALLET_PASSIVE_CHIP": "Pasif Gelir",
            "WALLET_STAKED_CHIP": "Blokeli",
            "SETTINGS_TITLE": "Ayarlar",
            "SETTINGS_HEADER_TITLE": "Kişisel Akış",
            "SETTINGS_HEADER_SUBTITLE": "Odak seansını sana göre özelleştir",
            "SETTINGS_HEADER_ACTION": "Güncelle",
            "SETTINGS_TILE_FOCUS": "Odak",
            "SETTINGS_TILE_BREAKS": "Molalar",
            "SETTINGS_TILE_LONG": "Uzun Mola",
            "SETTINGS_DURATION_SHORT_TITLE": "Kısa Mola",
            "SETTINGS_DURATION_LONG_TITLE": "Uzun Mola",
            "SETTINGS_SECTION_DURATIONS_TITLE": "Odak Süreleri",
            "SETTINGS_SECTION_DURATIONS_SUBTITLE": "Seans ve molaların ritmini seç",
            "SETTINGS_SECTION_GOALS_TITLE": "Hedefler",
            "SETTINGS_SECTION_GOALS_SUBTITLE": "Günlük planını ince ayarla",
            "SETTINGS_SECTION_ALERTS_TITLE": "Bildirimler",
            "SETTINGS_SECTION_ALERTS_SUBTITLE": "Pomodoro deneyimini kişiselleştir",
            "SETTINGS_SECTION_SOUND_TITLE": "Sayaç Sesi",
            "SETTINGS_SECTION_SOUND_SUBTITLE": "Tik tak ritmini seç ve yönet",
            "SETTINGS_SECTION_LANGUAGE_TITLE": "Uygulama Dili",
            "SETTINGS_SECTION_LANGUAGE_SUBTITLE": "Simpo'yu nasıl duymak istersin?",
            "SETTINGS_SECTION_THEME_TITLE": "Tema",
            "SETTINGS_SECTION_THEME_SUBTITLE": "Uygulamanın görünümünü seç",
            "THEME_SYSTEM": "Sistem Varsayılanı",
            "THEME_GRADIENT": "Gradient",
            "THEME_OLEDDARK": "OLED Dark",
            "THEME_LIGHT": "Light",
            "SETTINGS_SECTION_CREATOR_TITLE": "Yapımcı",
            "SETTINGS_SECTION_CREATOR_SUBTITLE": "Bana ulaşarak Simpo'yu birlikte geliştirelim",
            "SETTINGS_CREATOR_LINKEDIN": "LinkedIn",
            "SETTINGS_CREATOR_X": "X",
            "SETTINGS_CREATOR_EMAIL": "E-posta",
            "SETTINGS_CREATOR_EMAIL_SUBJECT": "Simpo geri bildirimi",
            "FOCUS_BACKGROUND_REFRESH_TITLE": "Arka planda yenileme kapalı",
            "FOCUS_BACKGROUND_REFRESH_MESSAGE": "Simpo'nun odak seansların tamamlandığında bildirim gönderebilmesi için Ayarlar > Genel > Arka Planda Uygulama Yenileme bölümünden Simpo'ya izin ver.",
            "FOCUS_BACKGROUND_REFRESH_BUTTON": "Ayarları aç",
            "SETTINGS_LANGUAGE_NOTE": "Bu tercih cihaz diline göre otomatik seçilir. Ayarlardan her zaman değiştirebilirsin.",
            "SETTINGS_DURATION_FORMAT": "%d dk",
            "FOCUS_PHASE_LABEL": "%@",
            "FOCUS_PHASE_PROGRESS": "İlerleme",
            "PHASE_FOCUS_LABEL": "Odak",
            "PHASE_SHORT_LABEL": "Kısa mola",
            "PHASE_LONG_LABEL": "Uzun mola",
            "PHASE_IDLE_LABEL": "Hazır",
            "TIMER_PHASE_FOCUS": "Odak",
            "TIMER_PHASE_SHORT": "Kısa mola",
            "TIMER_PHASE_LONG": "Uzun mola",
            "TIMER_PHASE_IDLE": "Hazır",
            "SETTINGS_STEPPER_DAILY": "Günlük pomodoro hedefi",
            "SETTINGS_STEPPER_LONG": "Uzun mola öncesi odak sayısı",
            "SETTINGS_TARGET_TITLE_DAILY": "Günlük hedef",
            "SETTINGS_TARGET_TITLE_LONG": "Uzun mola sayacı",
            "SETTINGS_UNIT_POMODORO": "pomodoro",
            "SETTINGS_UNIT_FOCUS": "odak",
            "SETTINGS_TARGET_LABEL": "Hedef: %d %@",
            "SETTINGS_TOGGLE_SOUND_TITLE": "Sesli Uyarılar",
            "SETTINGS_TOGGLE_SOUND_DESC": "Faz değişimlerinde ses oynat",
            "SETTINGS_TOGGLE_HAPTIC_TITLE": "Haptik Geri Bildirim",
            "SETTINGS_TOGGLE_HAPTIC_DESC": "Odak bitişlerinde titreşim",
            "SETTINGS_TOGGLE_AUTO_TITLE": "Molaları otomatik başlat",
            "SETTINGS_TOGGLE_AUTO_DESC": "Odak bitince mola otomatik başlasın",
            "SETTINGS_TOGGLE_NOTIF_TITLE": "Yerel Bildirimler",
            "SETTINGS_TOGGLE_NOTIF_DESC": "Uygulama arka plandayken uyarı gönder",
            "SETTINGS_TOGGLE_TICK_TITLE": "Sayaç sesi",
            "SETTINGS_TOGGLE_TICK_DESC": "Odak sırasında tik tak çalsın",
            "SETTINGS_TOGGLE_OVERRIDE_TITLE": "Sessiz modu yok say",
            "SETTINGS_TOGGLE_OVERRIDE_DESC": "Telefon sessizde olsa da çalsın",
            "SETTINGS_PICKER_TICK": "Ses",
            "TICK_SOUND_classic": "Klasik",
            "TICK_SOUND_wood": "Ahşap",
            "TICK_SOUND_digital": "Dijital",
            "TICK_SOUND_loFi": "Lo-Fi",
            "TICK_SOUND_glass": "Cam",
            "SETTINGS_BUTTON_PREVIEW": "Sesi Dinle",
            "SETTINGS_VOLUME_LABEL": "Ses Seviyesi",
            "SETTINGS_PERCENT_FORMAT": "%d%%",
            "SETTINGS_STEPPER_VALUE_SESSIONS": "%d seans",
            "SETTINGS_BUTTON_CANCEL": "İptal",
            "SETTINGS_BUTTON_SAVE": "Kaydet",
            "SETTINGS_LANGUAGE_PICKER": "Dil",
            "HOME_GUEST_NAME": "Simpo Dostu",
            "HOME_GREETING": "Merhaba, %@",
            "HOME_SUBTITLE": "Simpo evine hoş geldin. Çalışma alanını kişiselleştir, motivasyonunu artır.",
            "HOME_BUTTON_INVENTORY": "Envanter",
            "HOME_BALANCE_PRIMARY": "Cüzdan",
            "HOME_BALANCE_STAKED": "Faizde",
            "HOME_SEGMENT_OVERVIEW": "Özet",
            "HOME_SEGMENT_STUDIO": "Ev",
            "HOME_SEGMENT_MARKET": "Pazar",
            "HOME_ACTIVE_THEME_TITLE": "Aktif Tema",
            "HOME_ACTIVE_THEME_LABEL": "Tema atmosferi",
            "HOME_ACTIVE_THEME_BUTTON": "Dekorasyon",
            "HOME_STATS_TITLE": "Odak İstatistiklerin",
            "HOME_STATS_SUBTITLE": "Günlük hedefine yaklaşıyorsun",
            "HOME_STATS_COMPLETED": "Tamamlanan",
            "HOME_STATS_SPENT": "Harcanan",
            "HOME_STATS_PASSIVE": "Pasif Gelir",
            "HOME_THEME_BONUS": "%%%d enerji bonusu",
            "HOME_STUDIO_TITLE": "Yaşam Alanın",
            "HOME_STUDIO_SUBTITLE": "Yerleştirdiğin eşyaları anında düzenle.",
            "HOME_STUDIO_BUTTON": "Envanter",
            "HOME_STUDIO_EMPTY": "Henüz yerleştirdiğin eşya yok. Ev pazarından bir şeyler alarak başla.",
            "HOME_MARKET_TITLE": "Ev Pazarı",
            "HOME_MARKET_SUBTITLE": "Kazandığın coinlerle yeni dekorasyonlar keşfet.",
            "HOME_MARKET_PURCHASED": "Satın alındı",
            "HOME_DECOR_REMOVE": "Kaldır",
            "HOME_MARKET_SECTION_GENERIC": "%@",
            "HOME_PURCHASE_PLACE": "Yerleştir",
            "HOME_PURCHASE_BUY_PLACE": "Satın al ve yerleştir",
            "HOME_PURCHASE_PLACED": "%@ evine yerleştirildi",
            "HOME_PURCHASE_PURCHASED": "%@ satın alındı ve yerleştirildi",
            "HOME_PURCHASE_BALANCE_ERROR": "Bakiye yetersiz. Daha fazla coin kazanmalısın.",
            "HOME_OWNED_EMPTY": "Henüz satın aldığın eşya yok.",
            "HOME_NAV_CLOSE": "Kapat",
            "HOME_MARKET_SECTION_STARTER": "Başlangıç Paketi",
            "HOME_MARKET_SECTION_WORKSHOP": "Çalışma Alanı",
            "HOME_MARKET_SECTION_RELAX": "Dinlenme Köşesi",
            "HOME_MARKET_SECTION_COLLECTION": "Koleksiyon",
            "NOTIF_FOCUS_DONE_TITLE": "Odak tamamlandı",
            "NOTIF_FOCUS_DONE_BODY": "Harikasın! Artık hak ettiğin molayı verebilirsin.",
            "NOTIF_BREAK_DONE_TITLE": "Mola bitti",
            "NOTIF_BREAK_DONE_BODY": "Simpo seni bekliyor, hadi yeniden odaklan!",
            "ROOM_THEME_STARTER": "Başlangıç Ormanı",
            "ROOM_THEME_LAKE": "Göl Evi",
            "ROOM_ASSET_WOOD_DESK": "Ahşap Çalışma Masası",
            "ROOM_DESC_WOOD_DESK": "Minimal ve geniş çalışma alanı.",
            "ROOM_ASSET_FOCUS_TIMER": "FocusSand Zamanlayıcı",
            "ROOM_DESC_FOCUS_TIMER": "Seanslarını görsel olarak takip et.",
            "ROOM_ASSET_ERGO_CHAIR": "Ergonomik Sandalye",
            "ROOM_DESC_ERGO_CHAIR": "Uzun odak için konfor sunar.",
            "ROOM_ASSET_MEDITATION_MAT": "Meditasyon Minderi",
            "ROOM_DESC_MEDITATION_MAT": "Kısa molalarını dengeyle geçir.",
            "ROOM_ASSET_SILENT_PLANT": "Sessiz Bitki",
            "ROOM_DESC_SILENT_PLANT": "Odanı canlandıran monstre bitki.",
            "ROOM_ASSET_VINTAGE_LAMP": "Vintage Lamba",
            "ROOM_DESC_VINTAGE_LAMP": "Gece çalışmaları için sıcak ışık.",
            "ROOM_ASSET_RETRO_CONSOLE": "Retro Konsol",
            "ROOM_DESC_RETRO_CONSOLE": "Mola saatlerinde eğlenceli oyunlar.",
            "ROOM_ASSET_VINYL_PLAYER": "Vinil Çalar",
            "ROOM_DESC_VINYL_PLAYER": "Lo-fi listeni çal ve rahatla.",
            "ROOM_ASSET_MINI_LIBRARY": "Mini Kütüphane",
            "ROOM_DESC_MINI_LIBRARY": "Kitap koleksiyonunu sergile.",
            "ROOM_ASSET_MINI_PLANT": "Mini Bitki",
            "ROOM_DESC_MINI_PLANT": "Eve anında renk katar.",
            "ROOM_ASSET_BAMBOO_DESK": "Bambu Masa",
            "ROOM_DESC_BAMBOO_DESK": "Minimal bambu çalışma masası.",
            "ROOM_ASSET_ZEN_PLANT": "Zen Bitkisi",
            "ROOM_DESC_ZEN_PLANT": "Dikkatini toparlayan zen enerjisi.",
            "ROOM_ASSET_WARM_LIGHT": "Yumuşak Işık",
            "ROOM_DESC_WARM_LIGHT": "Sıcak ve rahat bir ışık.",
            "ROOM_ASSET_LAKE_VIEW": "Göl Manzarası",
            "ROOM_DESC_LAKE_VIEW": "Sessiz, huzurlu bir manzara.",
            "ROOM_ASSET_HAMMOCK": "Hamak",
            "ROOM_DESC_HAMMOCK": "Kısa molalar için ideal.",
            "ROOM_ASSET_WOOD_SHELF": "Ahşap Raf",
            "ROOM_DESC_WOOD_SHELF": "Kitaplarını düzenle.",
            "BUY_MARKET_CAP": "Piyasa Değeri",
            "BUY_AMOUNT_LABEL": "Tutar",
            "BUY_TOTAL_TITLE": "Alım Tutarı",
            "BUY_CONFIRM": "Satın Al",
            "BUY_CLOSE": "Kapat",
            "BUY_CONFIRM_SUCCESS": "%@ değerinde %@ aldın.",
            "BUY_INSUFFICIENT": "Bakiye yetersiz",
            "BUY_QUICK_AMOUNT": "Hızlı Tutar",
            "BUY_AMOUNT_TRY": "%@ TL",
            "BUY_AMOUNT_TOKEN": "%@ %@",
            "BUY_STATS_HELD": "Elindeki",
            "BUY_STATS_AVERAGE": "Ortalama",
            "BUY_STATS_MARKET": "Piyasa",
            "ONBOARD_STEP_WELCOME": "Simpo'ya Hoş Geldin",
            "ONBOARD_STEP_THEME": "Tema Seçimi",
            "ONBOARD_STEP_FOCUS": "Odak Ritmini Seç",
            "ONBOARD_STEP_BREAKS": "Mola Tercihlerini Belirle",
            "ONBOARD_STEP_FINANCE": "Kazanç ve Faiz Mantığı",
            "ONBOARD_STEP_HOME": "Evi Kişiselleştir",
            "ONBOARD_STEP_NOTIFICATIONS": "Bildirimleri Aç",
            "ONBOARD_STEP_PROFILE": "Seni Tanıyalım",
            "ONBOARD_SUB_WELCOME": "Odak süreni Simpo ile yönet. Birkaç adımda kişiselleştirelim.",
            "ONBOARD_SUB_THEME": "Uygulamanın görünümünü seç. İstediğin zaman değiştirebilirsin.",
            "ONBOARD_SUB_FOCUS": "Odak ve günlük hedef ayarlarını kendine göre yap.",
            "ONBOARD_SUB_BREAKS": "Kısa ve uzun mola sürelerini, otomatik başlatmayı seç.",
            "ONBOARD_SUB_FINANCE": "Kazancını nasıl artıracağını ve nerelerde harcayabileceğini öğren.",
            "ONBOARD_SUB_HOME": "Ev sekmesinde dekorasyon ve temalar seni bekliyor.",
            "ONBOARD_SUB_NOTIFICATIONS": "Odak veya mola bitince sana haber verelim mi?",
            "ONBOARD_SUB_PROFILE": "Son adım: seni nasıl çağıralım?",
            "ONBOARD_PRIMARY_NEXT": "İleri",
            "ONBOARD_PRIMARY_START": "Başla",
            "ONBOARD_BACK": "Geri",
            "ONBOARD_NAME_PROMPT": "Adın nedir?",
            "ONBOARD_NAME_HINT": "Bu ayarları Ayarlar ekranından her zaman değiştirebilirsin.",
            "ONBOARD_LANGUAGE_TITLE": "Dil Seçimi",
            "ONBOARD_LANGUAGE_DESCRIPTION": "Simpo'yu hangi dilde kullanmak istersin? (Varsayılan: cihaz dili)",
            "ONBOARD_LANGUAGE_NOTE": "Dil ayarını daha sonra Ayarlar ekranından değiştirebilirsin.",
            "ONBOARD_FOCUS_DURATION": "Odak süresi: %d dk",
            "ONBOARD_DAILY_TARGET": "Günlük hedef",
            "ONBOARD_DAILY_TARGET_VALUE": "%d pomodoro",
            "ONBOARD_SHORT_BREAK": "Kısa mola: %d dk",
            "ONBOARD_LONG_BREAK": "Uzun mola: %d dk",
            "ONBOARD_BEFORE_LONG_BREAK": "Uzun moladan önce %d odak",
            "ONBOARD_AUTO_BREAKS": "Molaları otomatik başlat",
            "ONBOARD_NOTIFICATIONS_TOGGLE": "Yerel bildirimleri aç",
            "ONBOARD_NOTIFICATIONS_DESC": "Odak veya molalar bittiğinde uyarı alırsın. Daha sonra Ayarlar ekranından değiştirilebilir.",
            "ONBOARD_FINANCE_EARN": "Pomodoro ile coin kazan",
            "ONBOARD_FINANCE_EARN_DESC": "Her odak seansı dakikası kadar coin (TL) kazandırır. Bu coinleri ev pazarında veya faiz hesabında değerlendirebilirsin.",
            "ONBOARD_FINANCE_BANK": "Faiz hesabına yatır",
            "ONBOARD_FINANCE_BANK_DESC": "Ana ekrandaki Banka sekmesinden coinlerini faize yatır, oranları takip et ve günlük getirini topla.",
            "ONBOARD_FINANCE_MARKET": "Pazarda harca",
            "ONBOARD_FINANCE_MARKET_DESC": "Market sekmesinden coin satın alabilir veya evini güzelleştirecek eşyalar alabilirsin.",
            "ONBOARD_HOME_CUSTOMIZE": "Evini kişiselleştir",
            "ONBOARD_HOME_CUSTOMIZE_DESC": "Ev sekmesinde kazandığın coinlerle eşya satın al, yerleştir ve envanterini yönet. Mini bitkiyle hemen başlayabilirsin.",
            "ONBOARD_HOME_THEMES": "Temalar & bonuslar",
            "ONBOARD_HOME_THEMES_DESC": "Tema değiştirerek çalışma alanının atmosferini değiştir, motivasyon bonusları kazan.",
            "ONBOARD_WELCOME_DESC": "Simpo seni daha üretken bir güne hazırlıyor. Birkaç tercihi seçelim.",
            "STATS_TOTAL_FOCUS_TIME": "Toplam Odak Süresi",
            "STATS_TOTAL_SESSIONS": "Toplam Seans",
            "STATS_ACTIVE_DAYS": "Aktif Gün",
            "STATS_AVERAGE_SESSION": "Ortalama",
            "STATS_PERFORMANCE_SUMMARY": "Performans Özeti",
            "STATS_BEST_STREAK": "En uzun seri",
            "STATS_STREAK_VALUE": "x%1$d seans",
            "STATS_DAILY_AVERAGE": "Günlük ortalama",
            "STATS_LAST_FOCUS": "Son odak",
            "STATS_LAST_FOCUS_NONE": "Henüz değil",
            "STATS_DAILY_GOAL": "Günlük Hedef",
            "STATS_GOAL_COMPLETE": "Bugünkü hedef tamamlandı!",
            "STATS_GOAL_PROGRESS": "Hedefe az kaldı, odaklanmaya devam et.",
            "STATS_ACTIVITY_CALENDAR": "Aktivite Takvimi",
            "STATS_ACTIVITY_DAYS": "Son %1$d gün",
            "STATS_HOURS_FORMAT": "%1$d s %2$d dk",
            "STATS_MINUTES_FORMAT": "%1$d dk",
            "STATS_GOAL_VALUE": "%1$d/%2$d",
            "BANK_STAKED": "Blokeli (faizde)",
            "BANK_EARNED": "Toplam kazanç",
            "BANK_YEARLY_RATE": "Yıllık faiz",
            "BANK_DAILY_RATE": "Günlük faiz",
            "BANK_ACTIONS": "İşlemler",
            "BANK_DEPOSIT_TITLE": "Faize Yatır",
            "BANK_DEPOSIT_SUB": "Kullanılabilir bakiyeyi artır",
            "BANK_WITHDRAW_TITLE": "Faizden Çek",
            "BANK_WITHDRAW_SUB": "Blokeli bakiyeyi serbest bırak",
            "BANK_AVAILABLE_LABEL": "Mevcut",
            "BANK_AMOUNT_PLACEHOLDER": "Tutar",
            "BANK_DEPOSIT_BUTTON": "Yatır",
            "BANK_WITHDRAW_BUTTON": "Çek",
            "BANK_INFO": "Faiz Bilgileri",
            "BANK_LAST_RATE": "Son faiz güncelleme",
            "BANK_LAST_INTEREST": "Son faiz yatırma",
            "BANK_ERROR_INVALID_DEPOSIT": "Yatırılacak tutar geçersiz",
            "BANK_ERROR_INVALID_WITHDRAW": "Çekilecek tutar geçersiz",
            "BANK_ERROR_INSUFFICIENT": "Yeterli bakiye yok (Kullanılabilir: %@)",
            "BANK_ERROR_OVER_STAKED": "Blokeli bakiyeden fazla çekilemez (Blokeli: %@)",
            "BANK_ERROR_GENERIC": "İşlem gerçekleştirilemedi",
            "BANK_SUCCESS_DEPOSIT": "%@ faize yatırıldı",
            "BANK_SUCCESS_WITHDRAW": "%@ çekildi",
            "FOCUS_NOW": "Şu an",
            "FOCUS_SUBTITLE_FOCUS": "Odaklanmaya devam et",
            "FOCUS_SUBTITLE_BREAK": "Molanın tadını çıkar",
            "SOUND_TITLE": "Sayaç Sesi",
            "STATE_ON": "Açık",
            "STATE_OFF": "Kapalı",
            "CONTROL_START": "Başlat",
            "CONTROL_PAUSE": "Duraklat",
            "CONTROL_SKIP": "Atla",
            "CONTROL_RESET": "Sıfırla",
            "STAT_STREAK": "Seri",
            "STAT_STREAK_VALUE": "x%d",
            "STAT_SESSIONS": "Oturum",
            "STAT_PHASE": "Faz",
            "GOAL_PHASE_PROGRESS": "Faz İlerleme",
            "GOAL_DAILY_TARGET": "Günlük Hedef",
            "SETTINGS_SECTION_BACKGROUND_TITLE": "Arka Plan Yenileme",
            "SETTINGS_SECTION_BACKGROUND_SUBTITLE": "Odak bildirimlerinin zamanında gelmesi için açık tut",
            "SETTINGS_BACKGROUND_READY_TITLE": "Bildirimler hazır",
            "SETTINGS_BACKGROUND_ALERT_TITLE": "Arka plan yenileme kapalı",
            "SETTINGS_BACKGROUND_ENABLE_NOTIF": "Simpo'nun bildirim gönderebilmesi için önce bildirim izni vermelisin.",
            "SETTINGS_BACKGROUND_ENABLE_REFRESH": "Bildirimlerin zamanında gelmesi için Ayarlar > Genel > Arka Planda Uygulama Yenileme bölümünden Simpo'yu etkinleştir.",
            "SETTINGS_BACKGROUND_ALL_GOOD": "Arka plan yenileme ve bildirim izinleri açık. Simpo hazır!",
            "SETTINGS_BACKGROUND_ALLOW_NOTIF": "Bildirim izni iste",
            "SETTINGS_BACKGROUND_OPEN_SETTINGS": "Simpo ayarlarını aç",
            "TXN_REWARD_POMODORO": "Pomodoro ödülü",
            "TXN_INTEREST_GAIN": "Faiz kazancı",
            "TXN_STAKE_DEPOSIT": "Faize yatırıldı",
            "TXN_STAKE_WITHDRAW": "Faiz hesabından çekildi",
            "TXN_THEME_UNLOCK": "%@ teması açıldı",
            "TXN_MARKET_BUY": "%@ satın alındı",
            "TXN_MARKET_SELL": "%@ satıldı",
            "CATEGORY_UNTAGGED": "Etiketlenmemiş",
            "CATEGORY_CODING": "Kodlama",
            "CATEGORY_ALGORITHMS": "Algoritmalar",
            "CATEGORY_PHYSICS": "Fizik",
            "CATEGORY_BUSINESS": "İş",
            "CATEGORY_MISC": "Diğer",
            "CATEGORY_TITLE": "Kategori",
            "CATEGORY_PICKER_TITLE": "Kategori Seç",
            "CATEGORY_PICKER_SUBTITLE": "Bu odak seansı için bir kategori seçin",
            "ANALYTICS_TITLE": "Yıllık Analitik",
            "ANALYTICS_TODAY": "Bugün",
            "ANALYTICS_WEEK": "Bu Hafta",
            "ANALYTICS_MONTH": "Bu Ay",
            "ANALYTICS_YEAR": "Bu Yıl",
            "ANALYTICS_ALL_TIME": "Tüm Zamanlar",
            "ANALYTICS_CATEGORY_BREAKDOWN": "Kategori Dağılımı",
            "ANALYTICS_BEST_RECORDS": "En İyi Kayıtlar",
            "ANALYTICS_BEST_DAY": "En İyi Gün",
            "ANALYTICS_BEST_WEEK": "En İyi Hafta",
            "ANALYTICS_BEST_MONTH": "En İyi Ay",
            "ANALYTICS_BEST_STREAK": "En İyi Seri",
            "ANALYTICS_ACTIVITY_CALENDAR": "Aktivite Takvimi",
            "ANALYTICS_NO_DATA": "Henüz veri yok",
            "ANALYTICS_DAYS": "gün",
            "ANALYTICS_CONSECUTIVE": "ardışık",
            "ANALYTICS_SESSIONS_COUNT": "%d oturum",
            "ANALYTICS_FOCUS_TIME": "Odak süresi",
            "ANALYTICS_SESSION": "oturum",
            "ANALYTICS_SESSIONS": "oturum",
            "CATEGORY_PREDEFINED": "Önceden Tanımlı",
            "CATEGORY_CUSTOM": "Özel Kategoriler",
            "ADD_CATEGORY_TITLE": "Yeni Kategori",
            "ADD_CATEGORY_SUBTITLE": "Kendi kategorini oluştur",
            "CATEGORY_NAME": "Kategori Adı",
            "CATEGORY_NAME_PLACEHOLDER": "Kategori adını girin",
            "CATEGORY_ICON": "İkon",
            "CATEGORY_COLOR": "Renk",
            "CATEGORY_PREVIEW": "Önizleme",
            "CANCEL": "İptal",
            "SAVE": "Kaydet",
            "SEARCH_CATEGORIES": "Kategorilerde ara...",
            "NO_CUSTOM_CATEGORIES": "Henüz özel kategori yok",
            "NO_CUSTOM_CATEGORIES_SUBTITLE": "İlk özel kategorini oluştur ve odak seanslarını organize et",
            "CREATE_FIRST_CATEGORY": "İlk Kategoriyi Oluştur",
            "PAYWALL_TITLE": "SimpoFocus Pro",
            "PAYWALL_SUBTITLE": "Tüm premium özellikleri aç, odaklanma deneyimini bir üst seviyeye taşı.",
            "PAYWALL_FEATURE_CATEGORIES": "Sınırsız özel kategori",
            "PAYWALL_FEATURE_ANALYTICS": "Gelişmiş analitik ve heatmap",
            "PAYWALL_FEATURE_THEMES": "Tüm temalar ve oda dekorasyonları",
            "PAYWALL_FEATURE_TIMER": "Gelişmiş zamanlayıcı ayarları",
            "PAYWALL_FEATURE_COINS": "2x coin kazanma çarpanı",
            "PAYWALL_PLAN_WEEKLY": "Haftalık",
            "PAYWALL_PLAN_MONTHLY": "Aylık",
            "PAYWALL_PLAN_YEARLY": "Yıllık",
            "PAYWALL_PERIOD_WEEK": "hafta",
            "PAYWALL_PERIOD_MONTH": "ay",
            "PAYWALL_PERIOD_YEAR": "yıl",
            "PAYWALL_BEST_VALUE": "En Avantajlı",
            "PAYWALL_SUBSCRIBE": "Abone Ol",
            "PAYWALL_ALREADY_PRO": "Zaten Pro",
            "PAYWALL_RESTORE": "Satın alımları geri yükle",
            "PAYWALL_TERMS": "Abonelik seçtiğiniz plana göre otomatik yenilenir. İstediğiniz zaman App Store ayarlarından iptal edebilirsiniz.",
            "SPECIAL_OFFER_WAIT": "Dur!",
            "SPECIAL_OFFER_TITLE": "Sana özel fırsat!",
            "SPECIAL_OFFER_SUBTITLE": "Sınırlı süre için %90 indirim",
            "SPECIAL_OFFER_ORIGINAL_PRICE": "Normal fiyat",
            "SPECIAL_OFFER_NOW": "Şimdi",
            "SPECIAL_OFFER_DISCOUNT_BADGE": "%90 İNDİRİM",
            "SPECIAL_OFFER_TIMER_LABEL": "Teklifin süresi",
            "SPECIAL_OFFER_CTA": "Teklifi Al",
            "SPECIAL_OFFER_NO_THANKS": "Hayır teşekkürler, belki sonra",
            "SPECIAL_OFFER_PER_WEEK": "/hafta",
            "ROOM_HEADER_TITLE": "Ev Temaları",
            "ROOM_HEADER_DESC": "Temaları keşfet, yeni atmosferler aç ve odanı motivasyonuna göre şekillendir.",
            "ROOM_ACTIVE_THEME": "AKTİF TEMA",
            "ROOM_THEME_EFFECT": "Temanın odaklanmana etkisi: +%%%d",
            "ROOM_CHOOSE_THEME": "Tema Seç",
            "ROOM_UNLOCK_HINT": "Yeni temalar açtıkça ev sekmesinde dekorasyon seçeneklerin artar.",
            "THEME_PRICE_COINS": "%d Coin",
            "SELL_COIN_QUANTITY_UNIT": "adet",
            "COIN_STORE_TITLE": "Coin Mağazası",
            "COIN_STORE_BALANCE": "Mevcut Bakiye",
            "COIN_STORE_SUCCESS_TITLE": "Satın Alma Başarılı",
            "COIN_STORE_SUCCESS_MSG": "%d coin hesabına eklendi!",
            "COIN_STORE_OK": "Tamam",
            "PRO_BADGE": "Pro",
            "PRO_GATE_ANALYTICS": "Gelişmiş analizler Pro ile açılır",
            "PRO_GATE_ANALYTICS_DESC": "Yıllık heatmap, kategori dağılımı ve en iyi kayıtlarını gör.",
            "PRO_GATE_UNLOCK": "Pro'ya Yükselt",
            "PRO_BANNER_TITLE": "2x Coin Çarpanı",
            "PRO_BANNER_SUBTITLE": "Pro ile aç",
            "PRO_COINSTORE_BANNER": "Pro ile tüm coinler 2x!",
            "PRO_COINSTORE_CTA": "Pro'ya Geç",
            "PRO_SESSION_NUDGE": "Pro ile 2x coin kazan",
            "ADD_CATEGORY_LIMIT": "%d/%d özel kategori (Pro ile sınırsız)",
            "THEME_PICKER_TITLE": "Tema Seç",
            "SETTINGS_DURATIONS_PRO_HINT": "Pro ile süreleri özelleştir",
            "TXN_COIN_PACK_PURCHASED": "Coin paketi satın alındı"
        ],
        .english: [
            "TAB_FOCUS": "Focus",
            "TAB_MARKET": "Market",
            "TAB_BANK": "Bank",
            "TAB_WALLET": "Wallet",
            "TAB_FINANCE": "Finance",
            "TAB_HOME": "Home",
            "FOCUS_NOW": "Now",
            "FOCUS_SUBTITLE_FOCUS": "Keep the focus going",
            "FOCUS_SUBTITLE_BREAK": "Enjoy your break",
            "SOUND_TITLE": "Timer Sound",
            "STATE_ON": "On",
            "STATE_OFF": "Off",
            "CONTROL_START": "Start",
            "CONTROL_PAUSE": "Pause",
            "CONTROL_SKIP": "Skip",
            "CONTROL_RESET": "Reset",
            "STAT_STREAK": "Streak",
            "STAT_STREAK_VALUE": "x%d",
            "STAT_SESSIONS": "Sessions",
            "STAT_PHASE": "Phase",
            "GOAL_PHASE_PROGRESS": "Phase progress",
            "GOAL_DAILY_TARGET": "Daily goal",
            "MARKET_TOTAL_BALANCE": "Total Balance",
            "MARKET_OVERVIEW": "Latest market snapshot",
            "MARKET_COINS": "Coins",
            "MARKET_SELL": "Sell",
            "MARKET_COIN_DESC_LEAF": "Focus coin: gain a boost after each session",
            "MARKET_COIN_DESC_ROOT": "Long-term: higher potential returns",
            "MARKET_COIN_DESC_BARK": "Balanced coin: lower volatility",
            "MARKET_COIN_DESC_DEFAULT": "Special coin",
            "SELL_COIN_SELECT": "Select Coin",
            "SELL_COIN_SELECT_PLACEHOLDER": "Select",
            "SELL_COIN_AVAILABLE": "Available: %@",
            "SELL_COIN_QUANTITY": "Quantity",
            "SELL_COIN_MARKET_VALUE": "Market Value",
            "SELL_COIN_CLOSE": "Close",
            "SELL_COIN_SELL": "Sell",
            "SELL_COIN_ERROR_SELECT": "Please select a coin",
            "SELL_COIN_ERROR_QUANTITY": "Quantity cannot be zero",
            "SELL_COIN_ERROR_INSUFFICIENT": "Insufficient coins",
            "BANK_ACCOUNT": "Bank Account",
            "BANK_AVAILABLE": "Available",
            "BANK_STAKED": "Locked (interest)",
            "BANK_EARNED": "Total interest",
            "BANK_YEARLY_RATE": "Annual rate",
            "BANK_DAILY_RATE": "Daily rate",
            "BANK_ACTIONS": "Actions",
            "BANK_DEPOSIT_TITLE": "Deposit",
            "BANK_DEPOSIT_SUB": "Increase your balance with savings",
            "BANK_WITHDRAW_TITLE": "Withdraw",
            "BANK_WITHDRAW_SUB": "Release your locked funds",
            "BANK_AVAILABLE_LABEL": "Available",
            "BANK_AMOUNT_PLACEHOLDER": "Amount",
            "BANK_DEPOSIT_BUTTON": "Deposit",
            "BANK_WITHDRAW_BUTTON": "Withdraw",
            "BANK_INFO": "Interest Details",
            "BANK_LAST_RATE": "Last rate update",
            "BANK_LAST_INTEREST": "Last interest applied",
            "BANK_ERROR_INVALID_DEPOSIT": "Invalid deposit amount",
            "BANK_ERROR_INVALID_WITHDRAW": "Invalid withdrawal amount",
            "BANK_ERROR_INSUFFICIENT": "Insufficient balance (Available: %@)",
            "BANK_ERROR_OVER_STAKED": "Cannot withdraw more than locked funds (Locked: %@)",
            "BANK_ERROR_GENERIC": "Transaction failed",
            "BANK_SUCCESS_DEPOSIT": "%@ deposited",
            "BANK_SUCCESS_WITHDRAW": "%@ withdrawn",
            "WALLET_TITLE": "Wallet",
            "WALLET_ASSETS": "Assets",
            "WALLET_EMPTY_ASSETS": "No investments yet",
            "WALLET_TRANSACTIONS": "Transactions",
            "WALLET_EMPTY_TRANSACTIONS": "No transactions yet",
            "WALLET_PASSIVE_TITLE": "Passive income balance",
            "WALLET_PASSIVE_RATE": "%d rate",
            "WALLET_SELL": "Sell",
            "WALLET_QUANTITY_SUFFIX": "%@ pcs",
            "WALLET_PASSIVE_CHIP": "Passive Boost",
            "WALLET_STAKED_CHIP": "Locked",
            "SETTINGS_TITLE": "Settings",
            "SETTINGS_HEADER_TITLE": "Personal Flow",
            "SETTINGS_HEADER_SUBTITLE": "Tailor your focus sessions to your style",
            "SETTINGS_HEADER_ACTION": "Update",
            "SETTINGS_TILE_FOCUS": "Focus",
            "SETTINGS_TILE_BREAKS": "Breaks",
            "SETTINGS_TILE_LONG": "Long Break",
            "SETTINGS_DURATION_SHORT_TITLE": "Short Break",
            "SETTINGS_DURATION_LONG_TITLE": "Long Break",
            "SETTINGS_SECTION_DURATIONS_TITLE": "Focus Durations",
            "SETTINGS_SECTION_DURATIONS_SUBTITLE": "Fine-tune focus and break lengths",
            "SETTINGS_SECTION_GOALS_TITLE": "Goals",
            "SETTINGS_SECTION_GOALS_SUBTITLE": "Adjust your daily plan",
            "SETTINGS_SECTION_ALERTS_TITLE": "Notifications",
            "SETTINGS_SECTION_ALERTS_SUBTITLE": "Personalize your pomodoro experience",
            "SETTINGS_SECTION_SOUND_TITLE": "Timer Sound",
            "SETTINGS_SECTION_SOUND_SUBTITLE": "Select and manage the ticking vibe",
            "SETTINGS_SECTION_LANGUAGE_TITLE": "App Language",
            "SETTINGS_SECTION_LANGUAGE_SUBTITLE": "How would you like Simpo to sound?",
            "SETTINGS_SECTION_THEME_TITLE": "Theme",
            "SETTINGS_SECTION_THEME_SUBTITLE": "Choose app appearance",
            "THEME_SYSTEM": "System Default",
            "THEME_GRADIENT": "Gradient",
            "THEME_OLEDDARK": "OLED Dark",
            "THEME_LIGHT": "Light",
            "SETTINGS_SECTION_CREATOR_TITLE": "Creator",
            "SETTINGS_SECTION_CREATOR_SUBTITLE": "Reach out and let's improve Simpo together",
            "SETTINGS_CREATOR_LINKEDIN": "LinkedIn",
            "SETTINGS_CREATOR_X": "X",
            "SETTINGS_CREATOR_EMAIL": "Email",
            "SETTINGS_CREATOR_EMAIL_SUBJECT": "Simpo feedback",
            "FOCUS_BACKGROUND_REFRESH_TITLE": "Background refresh disabled",
            "FOCUS_BACKGROUND_REFRESH_MESSAGE": "To deliver focus notifications on time, enable Background App Refresh for Simpo under Settings > General > Background App Refresh.",
            "FOCUS_BACKGROUND_REFRESH_BUTTON": "Open Settings",
            "SETTINGS_LANGUAGE_NOTE": "This choice defaults to your device language. You can update it anytime.",
            "SETTINGS_DURATION_FORMAT": "%d min",
            "FOCUS_PHASE_LABEL": "%@",
            "FOCUS_PHASE_PROGRESS": "Progress",
            "PHASE_FOCUS_LABEL": "Focus",
            "PHASE_SHORT_LABEL": "Short break",
            "PHASE_LONG_LABEL": "Long break",
            "PHASE_IDLE_LABEL": "Idle",
            "TIMER_PHASE_FOCUS": "Focus",
            "TIMER_PHASE_SHORT": "Short break",
            "TIMER_PHASE_LONG": "Long break",
            "TIMER_PHASE_IDLE": "Idle",
            "SETTINGS_STEPPER_DAILY": "Daily pomodoro target",
            "SETTINGS_STEPPER_LONG": "Focus sessions before a long break",
            "SETTINGS_TARGET_TITLE_DAILY": "Daily goal",
            "SETTINGS_TARGET_TITLE_LONG": "Long break counter",
            "SETTINGS_UNIT_POMODORO": "pomodoros",
            "SETTINGS_UNIT_FOCUS": "focus",
            "SETTINGS_TARGET_LABEL": "Goal: %d %@",
            "SETTINGS_TOGGLE_SOUND_TITLE": "Sound Alerts",
            "SETTINGS_TOGGLE_SOUND_DESC": "Play a sound when phases change",
            "SETTINGS_TOGGLE_HAPTIC_TITLE": "Haptic Feedback",
            "SETTINGS_TOGGLE_HAPTIC_DESC": "Vibrate when focus ends",
            "SETTINGS_TOGGLE_AUTO_TITLE": "Auto-start breaks",
            "SETTINGS_TOGGLE_AUTO_DESC": "Start the break automatically when focus ends",
            "SETTINGS_TOGGLE_NOTIF_TITLE": "Local Notifications",
            "SETTINGS_TOGGLE_NOTIF_DESC": "Send alerts when the app is in the background",
            "SETTINGS_TOGGLE_TICK_TITLE": "Ticking sound",
            "SETTINGS_TOGGLE_TICK_DESC": "Play ticking during focus",
            "SETTINGS_TOGGLE_OVERRIDE_TITLE": "Override silent mode",
            "SETTINGS_TOGGLE_OVERRIDE_DESC": "Play sound even if the device is muted",
            "SETTINGS_PICKER_TICK": "Sound",
            "TICK_SOUND_classic": "Classic",
            "TICK_SOUND_wood": "Wood",
            "TICK_SOUND_digital": "Digital",
            "TICK_SOUND_loFi": "Lo-Fi",
            "TICK_SOUND_glass": "Glass",
            "SETTINGS_BUTTON_PREVIEW": "Preview Sound",
            "SETTINGS_VOLUME_LABEL": "Volume",
            "SETTINGS_PERCENT_FORMAT": "%d%%",
            "SETTINGS_STEPPER_VALUE_SESSIONS": "%d sessions",
            "SETTINGS_BUTTON_CANCEL": "Cancel",
            "SETTINGS_BUTTON_SAVE": "Save",
            "SETTINGS_LANGUAGE_PICKER": "Language",
            "BUY_MARKET_CAP": "Market Cap",
            "BUY_AMOUNT_LABEL": "Amount",
            "BUY_TOTAL_TITLE": "Purchase Summary",
            "BUY_CONFIRM": "Buy",
            "BUY_CLOSE": "Close",
            "BUY_CONFIRM_SUCCESS": "You purchased %@ worth of %@.",
            "BUY_INSUFFICIENT": "Insufficient balance",
            "BUY_QUICK_AMOUNT": "Quick Amount",
            "BUY_AMOUNT_TRY": "%@ TRY",
            "BUY_AMOUNT_TOKEN": "%@ %@",
            "BUY_STATS_HELD": "Held",
            "BUY_STATS_AVERAGE": "Average",
            "BUY_STATS_MARKET": "Market",
            "ONBOARD_STEP_WELCOME": "Welcome to Simpo",
            "ONBOARD_STEP_THEME": "Choose Theme",
            "ONBOARD_STEP_FOCUS": "Choose Your Focus Rhythm",
            "ONBOARD_STEP_BREAKS": "Set Your Break Preferences",
            "ONBOARD_STEP_FINANCE": "Understand Earnings & Interest",
            "ONBOARD_STEP_HOME": "Customize Your Home",
            "ONBOARD_STEP_NOTIFICATIONS": "Enable Notifications",
            "ONBOARD_STEP_PROFILE": "Tell Us About You",
            "ONBOARD_SUB_WELCOME": "Manage your focus time with Simpo. Let's personalize it in a few steps.",
            "ONBOARD_SUB_THEME": "Choose the app appearance. You can change it anytime.",
            "ONBOARD_SUB_FOCUS": "Configure your focus durations and daily targets.",
            "ONBOARD_SUB_BREAKS": "Pick short and long break durations and auto-start preferences.",
            "ONBOARD_SUB_FINANCE": "Learn how to earn coins and where to spend them.",
            "ONBOARD_SUB_HOME": "Decor items and themes await in the Home tab.",
            "ONBOARD_SUB_NOTIFICATIONS": "Stay notified when focus or breaks end.",
            "ONBOARD_SUB_PROFILE": "Final step: how should Simpo call you?",
            "ONBOARD_PRIMARY_NEXT": "Next",
            "ONBOARD_PRIMARY_START": "Start",
            "ONBOARD_BACK": "Back",
            "ONBOARD_NAME_PROMPT": "What's your name?",
            "ONBOARD_NAME_HINT": "You can change these settings anytime in Settings.",
            "ONBOARD_LANGUAGE_TITLE": "Choose Language",
            "ONBOARD_LANGUAGE_DESCRIPTION": "Which language would you like to use Simpo in? (Default: device language)",
            "ONBOARD_LANGUAGE_NOTE": "You can change the language later from Settings.",
            "ONBOARD_FOCUS_DURATION": "Focus duration: %d min",
            "ONBOARD_DAILY_TARGET": "Daily goal",
            "ONBOARD_DAILY_TARGET_VALUE": "%d pomodoros",
            "ONBOARD_SHORT_BREAK": "Short break: %d min",
            "ONBOARD_LONG_BREAK": "Long break: %d min",
            "ONBOARD_BEFORE_LONG_BREAK": "%d focus sessions before long break",
            "ONBOARD_AUTO_BREAKS": "Auto-start breaks",
            "ONBOARD_NOTIFICATIONS_TOGGLE": "Enable local notifications",
            "ONBOARD_NOTIFICATIONS_DESC": "Stay notified when focus or breaks end. You can change this later in Settings.",
            "ONBOARD_FINANCE_EARN": "Earn coins with pomodoros",
            "ONBOARD_FINANCE_EARN_DESC": "Each focused minute rewards you with coins to invest or spend.",
            "ONBOARD_FINANCE_BANK": "Grow with interest",
            "ONBOARD_FINANCE_BANK_DESC": "Use the Bank tab to stake coins, track rates, and collect earnings.",
            "ONBOARD_FINANCE_MARKET": "Spend in the market",
            "ONBOARD_FINANCE_MARKET_DESC": "Buy coins or items to decorate your space.",
            "ONBOARD_HOME_CUSTOMIZE": "Customize your home",
            "ONBOARD_HOME_CUSTOMIZE_DESC": "Spend your coins to decorate and manage your inventory.",
            "ONBOARD_HOME_THEMES": "Themes & boosts",
            "ONBOARD_HOME_THEMES_DESC": "Switch themes to refresh your workspace and earn boosts.",
            "ONBOARD_WELCOME_DESC": "Simpo helps you start a productive day. Let's pick a few preferences.",
            "STATS_TOTAL_FOCUS_TIME": "Total Focus Time",
            "STATS_TOTAL_SESSIONS": "Total Sessions",
            "STATS_ACTIVE_DAYS": "Active Days",
            "STATS_AVERAGE_SESSION": "Average",
            "STATS_PERFORMANCE_SUMMARY": "Performance Summary",
            "STATS_BEST_STREAK": "Longest streak",
            "STATS_STREAK_VALUE": "x%1$d sessions",
            "STATS_DAILY_AVERAGE": "Daily average",
            "STATS_LAST_FOCUS": "Last focus",
            "STATS_LAST_FOCUS_NONE": "Not yet",
            "STATS_DAILY_GOAL": "Daily Goal",
            "STATS_GOAL_COMPLETE": "Today's goal is complete!",
            "STATS_GOAL_PROGRESS": "Almost there, keep your focus.",
            "STATS_ACTIVITY_CALENDAR": "Activity Calendar",
            "STATS_ACTIVITY_DAYS": "Last %1$d days",
            "STATS_HOURS_FORMAT": "%1$d h %2$d min",
            "STATS_MINUTES_FORMAT": "%1$d min",
            "STATS_GOAL_VALUE": "%1$d/%2$d",
            "Dili Ayarla": "Change Language",
            "Uygulama dilini seç": "Choose the app language",
            "Bu tercih cihaz diline göre otomatik seçilir. Ayarlardan her zaman değiştirebilirsin.": "Defaults to your device language. You can change it anytime.",
            "_settings_title": "Settings",
            "settings_language_subtitle": "Choose the app language",
            "settings_language_hint": "This follows your device language by default. You can change it any time.",
            "Simpo'ya Hoş Geldin": "Welcome to Simpo",
            "Odak süreni Simpo ile yönet. Birkaç adımda kişiselleştirelim.": "Manage your focus time with Simpo. Let's personalize it in a few steps.",
            "Odak Ritmini Seç": "Choose Your Focus Rhythm",
            "Odak ve günlük hedef ayarlarını kendine göre yap.": "Configure your focus durations and daily targets.",
            "Mola Tercihlerini Belirle": "Set Your Break Preferences",
            "Kısa ve uzun mola sürelerini, otomatik başlatmayı seç.": "Choose short and long break durations, and whether breaks auto-start.",
            "Kazanç ve Faiz Mantığı": "Earnings & Interest",
            "Kazancını nasıl artıracağını und wo du sie ausgeben kannst.": "Learn how to earn coins and where you can spend them.",
            "Evini Kişiselleştir": "Customize Your Home",
            "Ev sekmesinde dekorasyon und Themen warten im Zuhause-Tab auf dich.": "Decor items and themes await you in the Home tab.",
            "Bildirimleri Açalım": "Enable Notifications",
            "Odak und Pausenende benachrichtigt werden?": "Would you like to be notified when a focus or break session ends?",
            "Seni Tanıyalım": "Tell Us About You",
            "Son adım: seni nasıl çağıralım?": "Final step: how should we call you?",
            "Focus Forest seni daha üretken bir güne hazırlıyor. Birkaç tercihi seçelim.": "Focus Forest helps you start a productive day. Let's pick a few preferences.",
            "Günlük hedef": "Daily target",
            "Uzun moladan önce %d odak": "Take a long break after %d focus sessions",
            "Molaları otomatik başlat": "Auto-start breaks",
            "Yerel bildirimleri aç": "Enable local notifications",
            "Bu ayarları Ayarlar ekranından her zaman değiştirebilirsin.": "You can always change these settings from the Settings screen.",
            "Başla": "Get Started",
            "İleri": "Next",
            "Merhaba, %@ 👋": "Hello, %@ 👋",
            "Evini dilediğin gibi düzenle. Kazandığın coinlerle dekorasyon ürünleri satın al ve çalışma alanını kişiselleştir.": "Arrange your home the way you like. Spend your coins on decor and personalize your workspace.",
            "Ev Pazarı": "Home Market",
            "Kazandığın coinlerle yeni dekorasyonlar keşfet.": "Discover new decor items with your coins.",
            "Yaşam Alanın": "Your Living Space",
            "Yerleştirdiğin eşyaları anında düzenle.": "Organize the items you've placed instantly.",
            "Henüz yerleştirdiğin eşya yok. Ev pazarından bir şeyler alarak başla.": "You haven't placed any items yet. Start by buying something from the Home Market.",
            "Merhaba": "Hello",
            "Varlıklar": "Assets",
            "Henüz yatırım yapmadın": "You haven't made an investment yet.",
            "Sat": "Sell",
            "Cüzdan": "Wallet",
            "Pasif kazanç birikimi": "Passive income balance",
            "Henüz işlem yok": "No transactions yet",
            "Hareketler": "Transactions",
            "Faize Yatır": "Deposit to interest",
            "Faizden Çek": "Withdraw from interest",
            "Yatır": "Deposit",
            "Çek": "Withdraw",
            "Yatırılacak tutar geçersiz": "Invalid deposit amount",
            "Yeterli bakiye yok (Kullanılabilir: %@)": "Insufficient balance (Available: %@)",
            "₺%.2f faize yatırıldı": "₺%.2f deposited to interest",
            "İşlem gerçekleştirilemedi": "Transaction failed",
            "Çekilecek tutar geçersiz": "Invalid withdraw amount",
            "Blokeli bakiyeden fazla çekilemez (Blokeli: %@)": "Cannot withdraw more than the locked balance (Locked: %@)",
            "₺%.2f çekildi": "₺%.2f withdrawn",
            "Banka Hesabı": "Bank Account",
            "Kullanılabilir": "Available",
            "Blokeli (faizde)": "Locked (interest)",
            "Toplam kazanç": "Total interest",
            "Yıllık faiz": "Annual rate",
            "Günlük faiz": "Daily rate",
            "İşlemler": "Actions",
            "Evini kişiselleştir": "Customize your home",
            "HOME_GUEST_NAME": "Simpo Friend",
            "HOME_GREETING": "Hello, %@",
            "HOME_SUBTITLE": "Welcome back to your Simpo home. Personalize your space and boost your motivation.",
            "HOME_BUTTON_INVENTORY": "Inventory",
            "HOME_BALANCE_PRIMARY": "Wallet",
            "HOME_BALANCE_STAKED": "Staked",
            "HOME_SEGMENT_OVERVIEW": "Overview",
            "HOME_SEGMENT_STUDIO": "Home",
            "HOME_SEGMENT_MARKET": "Market",
            "HOME_ACTIVE_THEME_TITLE": "Active Theme",
            "HOME_ACTIVE_THEME_LABEL": "Theme atmosphere",
            "HOME_ACTIVE_THEME_BUTTON": "Decor",
            "HOME_STATS_TITLE": "Focus Stats",
            "HOME_STATS_SUBTITLE": "You're getting closer to your daily goal",
            "HOME_STATS_COMPLETED": "Completed",
            "HOME_STATS_SPENT": "Spent",
            "HOME_STATS_PASSIVE": "Passive",
            "HOME_THEME_BONUS": "%d%% energy bonus",
            "HOME_STUDIO_TITLE": "Your Space",
            "HOME_STUDIO_SUBTITLE": "Manage placed items instantly.",
            "HOME_STUDIO_BUTTON": "Inventory",
            "HOME_STUDIO_EMPTY": "You haven't placed any items yet. Start by picking something from the Home Market.",
            "HOME_MARKET_TITLE": "Home Market",
            "HOME_MARKET_SUBTITLE": "Discover new decor with the coins you've earned.",
            "HOME_MARKET_PURCHASED": "Owned",
            "HOME_DECOR_REMOVE": "Remove",
            "HOME_MARKET_SECTION_GENERIC": "%@",
            "HOME_MARKET_SECTION_STARTER": "Starter Pack",
            "HOME_MARKET_SECTION_WORKSHOP": "Workspace",
            "HOME_MARKET_SECTION_RELAX": "Relax Corner",
            "HOME_MARKET_SECTION_COLLECTION": "Collection",
            "NOTIF_FOCUS_DONE_TITLE": "Focus complete",
            "NOTIF_FOCUS_DONE_BODY": "Great job! Time to enjoy a well-deserved break.",
            "NOTIF_BREAK_DONE_TITLE": "Break finished",
            "NOTIF_BREAK_DONE_BODY": "Let's jump back into focus with Simpo.",
            "ROOM_THEME_STARTER": "Starter Grove",
            "ROOM_THEME_LAKE": "Lake House",
            "ROOM_ASSET_WOOD_DESK": "Wooden Desk",
            "ROOM_DESC_WOOD_DESK": "A spacious, minimal workspace.",
            "ROOM_ASSET_FOCUS_TIMER": "FocusSand Timer",
            "ROOM_DESC_FOCUS_TIMER": "Track sessions with a visual hourglass.",
            "ROOM_ASSET_ERGO_CHAIR": "Ergonomic Chair",
            "ROOM_DESC_ERGO_CHAIR": "Comfort that supports long focus.",
            "ROOM_ASSET_MEDITATION_MAT": "Meditation Mat",
            "ROOM_DESC_MEDITATION_MAT": "Balance your short breaks with mindfulness.",
            "ROOM_ASSET_SILENT_PLANT": "Silent Plant",
            "ROOM_DESC_SILENT_PLANT": "A calming monstera that lifts the room.",
            "ROOM_ASSET_VINTAGE_LAMP": "Vintage Lamp",
            "ROOM_DESC_VINTAGE_LAMP": "Warm light for late-night sessions.",
            "ROOM_ASSET_RETRO_CONSOLE": "Retro Console",
            "ROOM_DESC_RETRO_CONSOLE": "Play a quick game during breaks.",
            "ROOM_ASSET_VINYL_PLAYER": "Vinyl Player",
            "ROOM_DESC_VINYL_PLAYER": "Spin your lo-fi playlist in style.",
            "ROOM_ASSET_MINI_LIBRARY": "Mini Library",
            "ROOM_DESC_MINI_LIBRARY": "Showcase your favorite reads.",
            "ROOM_ASSET_MINI_PLANT": "Mini Plant",
            "ROOM_DESC_MINI_PLANT": "Add instant color to your space.",
            "ROOM_ASSET_BAMBOO_DESK": "Bamboo Desk",
            "ROOM_DESC_BAMBOO_DESK": "A minimalist desk made of bamboo.",
            "ROOM_ASSET_ZEN_PLANT": "Zen Plant",
            "ROOM_DESC_ZEN_PLANT": "Brings calm, focused energy to your space.",
            "ROOM_ASSET_WARM_LIGHT": "Soft Light",
            "ROOM_DESC_WARM_LIGHT": "Gentle lighting for a cozy mood.",
            "ROOM_ASSET_LAKE_VIEW": "Lake View",
            "ROOM_DESC_LAKE_VIEW": "A serene lakeside landscape to gaze at.",
            "ROOM_ASSET_HAMMOCK": "Hammock",
            "ROOM_DESC_HAMMOCK": "Ideal for relaxing breaks.",
            "ROOM_ASSET_WOOD_SHELF": "Wood Shelf",
            "ROOM_DESC_WOOD_SHELF": "Keep your books within easy reach.",
            "HOME_PURCHASE_PLACE": "Place",
            "HOME_PURCHASE_BUY_PLACE": "Buy & place",
            "HOME_PURCHASE_PLACED": "%@ was placed in your home",
            "HOME_PURCHASE_PURCHASED": "%@ purchased and placed",
            "HOME_PURCHASE_BALANCE_ERROR": "Insufficient balance. Earn more coins.",
            "HOME_OWNED_EMPTY": "You haven't purchased any items yet.",
            "HOME_NAV_CLOSE": "Close",
            "SETTINGS_SECTION_BACKGROUND_TITLE": "Background Refresh",
            "SETTINGS_SECTION_BACKGROUND_SUBTITLE": "Keep it on so focus alerts arrive on time",
            "SETTINGS_BACKGROUND_READY_TITLE": "Notifications ready",
            "SETTINGS_BACKGROUND_ALERT_TITLE": "Background refresh disabled",
            "SETTINGS_BACKGROUND_ENABLE_NOTIF": "Allow notification permission so Simpo can alert you when sessions finish.",
            "SETTINGS_BACKGROUND_ENABLE_REFRESH": "Enable Background App Refresh for Simpo under Settings > General so alerts aren't delayed.",
            "SETTINGS_BACKGROUND_ALL_GOOD": "Background refresh and notification permissions are active. Simpo is all set!",
            "SETTINGS_BACKGROUND_ALLOW_NOTIF": "Request notification access",
            "SETTINGS_BACKGROUND_OPEN_SETTINGS": "Open Simpo settings",
            "TXN_REWARD_POMODORO": "Pomodoro reward",
            "TXN_INTEREST_GAIN": "Interest earned",
            "TXN_STAKE_DEPOSIT": "Deposited to interest",
            "TXN_STAKE_WITHDRAW": "Withdrawn from interest",
            "TXN_THEME_UNLOCK": "%@ theme unlocked",
            "TXN_MARKET_BUY": "%@ bought",
            "TXN_MARKET_SELL": "%@ sold",
            "CATEGORY_UNTAGGED": "Untagged",
            "CATEGORY_CODING": "Coding",
            "CATEGORY_ALGORITHMS": "Algorithms",
            "CATEGORY_PHYSICS": "Physics",
            "CATEGORY_BUSINESS": "Business",
            "CATEGORY_MISC": "Misc",
            "CATEGORY_TITLE": "Category",
            "CATEGORY_PICKER_TITLE": "Select Category",
            "CATEGORY_PICKER_SUBTITLE": "Choose a category for this focus session",
            "ANALYTICS_TITLE": "Yearly Analytics",
            "ANALYTICS_TODAY": "Today",
            "ANALYTICS_WEEK": "This Week",
            "ANALYTICS_MONTH": "This Month",
            "ANALYTICS_YEAR": "This Year",
            "ANALYTICS_ALL_TIME": "All Time",
            "ANALYTICS_CATEGORY_BREAKDOWN": "Category Breakdown",
            "ANALYTICS_BEST_RECORDS": "Best Records",
            "ANALYTICS_BEST_DAY": "Best Day",
            "ANALYTICS_BEST_WEEK": "Best Week",
            "ANALYTICS_BEST_MONTH": "Best Month",
            "ANALYTICS_BEST_STREAK": "Best Streak",
            "ANALYTICS_ACTIVITY_CALENDAR": "Activity Calendar",
            "ANALYTICS_NO_DATA": "No data yet",
            "ANALYTICS_DAYS": "days",
            "ANALYTICS_CONSECUTIVE": "consecutive",
            "ANALYTICS_SESSIONS_COUNT": "%d sessions",
            "ANALYTICS_FOCUS_TIME": "Focus time",
            "ANALYTICS_SESSION": "session",
            "ANALYTICS_SESSIONS": "sessions",
            "CATEGORY_PREDEFINED": "Predefined",
            "CATEGORY_CUSTOM": "Custom Categories",
            "ADD_CATEGORY_TITLE": "New Category",
            "ADD_CATEGORY_SUBTITLE": "Create your own category",
            "CATEGORY_NAME": "Category Name",
            "CATEGORY_NAME_PLACEHOLDER": "Enter category name",
            "CATEGORY_ICON": "Icon",
            "CATEGORY_COLOR": "Color",
            "CATEGORY_PREVIEW": "Preview",
            "CANCEL": "Cancel",
            "SAVE": "Save",
            "SEARCH_CATEGORIES": "Search categories...",
            "NO_CUSTOM_CATEGORIES": "No custom categories yet",
            "NO_CUSTOM_CATEGORIES_SUBTITLE": "Create your first custom category and organize your focus sessions",
            "CREATE_FIRST_CATEGORY": "Create First Category",
            "PAYWALL_TITLE": "SimpoFocus Pro",
            "PAYWALL_SUBTITLE": "Unlock all premium features and take your focus experience to the next level.",
            "PAYWALL_FEATURE_CATEGORIES": "Unlimited custom categories",
            "PAYWALL_FEATURE_ANALYTICS": "Advanced analytics & heatmap",
            "PAYWALL_FEATURE_THEMES": "All themes and room decorations",
            "PAYWALL_FEATURE_TIMER": "Advanced timer settings",
            "PAYWALL_FEATURE_COINS": "2x coin earning multiplier",
            "PAYWALL_PLAN_WEEKLY": "Weekly",
            "PAYWALL_PLAN_MONTHLY": "Monthly",
            "PAYWALL_PLAN_YEARLY": "Yearly",
            "PAYWALL_PERIOD_WEEK": "week",
            "PAYWALL_PERIOD_MONTH": "month",
            "PAYWALL_PERIOD_YEAR": "year",
            "PAYWALL_BEST_VALUE": "Best Value",
            "PAYWALL_SUBSCRIBE": "Subscribe",
            "PAYWALL_ALREADY_PRO": "Already Pro",
            "PAYWALL_RESTORE": "Restore purchases",
            "PAYWALL_TERMS": "Subscription auto-renews based on your selected plan. You can cancel anytime from App Store settings.",
            "SPECIAL_OFFER_WAIT": "Wait!",
            "SPECIAL_OFFER_TITLE": "Special offer just for you!",
            "SPECIAL_OFFER_SUBTITLE": "90% off for a limited time",
            "SPECIAL_OFFER_ORIGINAL_PRICE": "Regular price",
            "SPECIAL_OFFER_NOW": "Now",
            "SPECIAL_OFFER_DISCOUNT_BADGE": "90% OFF",
            "SPECIAL_OFFER_TIMER_LABEL": "Offer expires in",
            "SPECIAL_OFFER_CTA": "Claim Your Offer",
            "SPECIAL_OFFER_NO_THANKS": "No thanks, maybe later",
            "SPECIAL_OFFER_PER_WEEK": "/week",
            "ROOM_HEADER_TITLE": "Room Themes",
            "ROOM_HEADER_DESC": "Explore themes, unlock new atmospheres, and shape your room to match your motivation.",
            "ROOM_ACTIVE_THEME": "ACTIVE THEME",
            "ROOM_THEME_EFFECT": "Theme focus boost: +%d%%",
            "ROOM_CHOOSE_THEME": "Choose Theme",
            "ROOM_UNLOCK_HINT": "As you unlock new themes, more decoration options appear in the home tab.",
            "THEME_PRICE_COINS": "%d Coins",
            "SELL_COIN_QUANTITY_UNIT": "units",
            "COIN_STORE_TITLE": "Coin Store",
            "COIN_STORE_BALANCE": "Current Balance",
            "COIN_STORE_SUCCESS_TITLE": "Purchase Successful",
            "COIN_STORE_SUCCESS_MSG": "%d coins added to your account!",
            "COIN_STORE_OK": "OK",
            "PRO_BADGE": "Pro",
            "PRO_GATE_ANALYTICS": "Advanced analytics unlocked with Pro",
            "PRO_GATE_ANALYTICS_DESC": "View yearly heatmap, category breakdown, and best records.",
            "PRO_GATE_UNLOCK": "Upgrade to Pro",
            "PRO_BANNER_TITLE": "2x Coin Multiplier",
            "PRO_BANNER_SUBTITLE": "Unlock with Pro",
            "PRO_COINSTORE_BANNER": "All coins 2x with Pro!",
            "PRO_COINSTORE_CTA": "Get Pro",
            "PRO_SESSION_NUDGE": "Earn 2x coins with Pro",
            "ADD_CATEGORY_LIMIT": "%d/%d custom categories (unlimited with Pro)",
            "THEME_PICKER_TITLE": "Choose Theme",
            "SETTINGS_DURATIONS_PRO_HINT": "Customize durations with Pro",
            "TXN_COIN_PACK_PURCHASED": "Coin pack purchased"
        ],
        .german: [
            "TAB_FOCUS": "Fokus",
            "TAB_MARKET": "Markt",
            "TAB_BANK": "Bank",
            "TAB_WALLET": "Geldbörse",
            "TAB_FINANCE": "Finanzen",
            "TAB_HOME": "Zuhause",
            "FOCUS_NOW": "Jetzt",
            "FOCUS_SUBTITLE_FOCUS": "Bleib konzentriert",
            "FOCUS_SUBTITLE_BREAK": "Genieß deine Pause",
            "SOUND_TITLE": "Timer-Sound",
            "STATE_ON": "An",
            "STATE_OFF": "Aus",
            "CONTROL_START": "Start",
            "CONTROL_PAUSE": "Pause",
            "CONTROL_SKIP": "Überspringen",
            "CONTROL_RESET": "Zurücksetzen",
            "STAT_STREAK": "Serie",
            "STAT_STREAK_VALUE": "x%d",
            "STAT_SESSIONS": "Sitzungen",
            "STAT_PHASE": "Phase",
            "GOAL_PHASE_PROGRESS": "Phasenfortschritt",
            "GOAL_DAILY_TARGET": "Tagesziel",
            "MARKET_TOTAL_BALANCE": "Gesamtsaldo",
            "MARKET_OVERVIEW": "Aktueller Marktüberblick",
            "MARKET_COINS": "Coins",
            "MARKET_SELL": "Verkaufen",
            "MARKET_COIN_DESC_LEAF": "Fokus-Coin: kleiner Bonus nach jeder Session",
            "MARKET_COIN_DESC_ROOT": "Langfristig: höhere Renditechance",
            "MARKET_COIN_DESC_BARK": "Ausgewogener Coin: geringere Volatilität",
            "MARKET_COIN_DESC_DEFAULT": "Spezialcoin",
            "SELL_COIN_SELECT": "Coin wählen",
            "SELL_COIN_SELECT_PLACEHOLDER": "Auswählen",
            "SELL_COIN_AVAILABLE": "Verfügbar: %@",
            "SELL_COIN_QUANTITY": "Menge",
            "SELL_COIN_MARKET_VALUE": "Marktwert",
            "SELL_COIN_CLOSE": "Schließen",
            "SELL_COIN_SELL": "Verkaufen",
            "SELL_COIN_ERROR_SELECT": "Bitte wähle einen Coin",
            "SELL_COIN_ERROR_QUANTITY": "Menge kann nicht null sein",
            "SELL_COIN_ERROR_INSUFFICIENT": "Unzureichende Coins",
            "BANK_ACCOUNT": "Bankkonto",
            "BANK_AVAILABLE": "Verfügbar",
            "BANK_STAKED": "Gesperrt (Zinsen)",
            "BANK_EARNED": "Gesamteinnahmen",
            "BANK_YEARLY_RATE": "Jahreszins",
            "BANK_DAILY_RATE": "Tageszins",
            "BANK_ACTIONS": "Aktionen",
            "BANK_DEPOSIT_TITLE": "Anlegen",
            "BANK_DEPOSIT_SUB": "Verfügbares Guthaben erhöhen",
            "BANK_WITHDRAW_TITLE": "Abheben",
            "BANK_WITHDRAW_SUB": "Gesperrtes Guthaben freigeben",
            "BANK_AVAILABLE_LABEL": "Verfügbar",
            "BANK_AMOUNT_PLACEHOLDER": "Betrag",
            "BANK_DEPOSIT_BUTTON": "Anlegen",
            "BANK_WITHDRAW_BUTTON": "Abheben",
            "BANK_INFO": "Zinsinformationen",
            "BANK_LAST_RATE": "Letzte Zinsanpassung",
            "BANK_LAST_INTEREST": "Letzte Zinsgutschrift",
            "BANK_ERROR_INVALID_DEPOSIT": "Ungültiger Anlagebetrag",
            "BANK_ERROR_INVALID_WITHDRAW": "Ungültiger Abhebebetrag",
            "BANK_ERROR_INSUFFICIENT": "Nicht genug Guthaben (Verfügbar: %@)",
            "BANK_ERROR_OVER_STAKED": "Es kann nicht mehr als der gesperrte Betrag abgehoben werden (Gesperrt: %@)",
            "BANK_ERROR_GENERIC": "Transaktion fehlgeschlagen",
            "BANK_SUCCESS_DEPOSIT": "%@ angelegt",
            "BANK_SUCCESS_WITHDRAW": "%@ abgehoben",
            "WALLET_TITLE": "Geldbörse",
            "WALLET_ASSETS": "Vermögenswerte",
            "WALLET_EMPTY_ASSETS": "Noch keine Investitionen",
            "WALLET_TRANSACTIONS": "Transaktionen",
            "WALLET_EMPTY_TRANSACTIONS": "Noch keine Transaktionen",
            "WALLET_PASSIVE_TITLE": "Passive Einnahmen",
            "WALLET_PASSIVE_RATE": "%d Rate",
            "WALLET_SELL": "Verkaufen",
            "WALLET_QUANTITY_SUFFIX": "%@ Stk",
            "WALLET_PASSIVE_CHIP": "Passiver Boost",
            "WALLET_STAKED_CHIP": "Gesperrt",
            "SETTINGS_TITLE": "Einstellungen",
            "SETTINGS_HEADER_TITLE": "Eigener Rhythmus",
            "SETTINGS_HEADER_SUBTITLE": "Passe deine Fokus-Sessions an deinen Rhythmus an",
            "SETTINGS_HEADER_ACTION": "Aktualisieren",
            "SETTINGS_TILE_FOCUS": "Fokus",
            "SETTINGS_TILE_BREAKS": "Pausen",
            "SETTINGS_TILE_LONG": "Lange Pause",
            "SETTINGS_DURATION_SHORT_TITLE": "Kurze Pause",
            "SETTINGS_DURATION_LONG_TITLE": "Lange Pause",
            "SETTINGS_SECTION_DURATIONS_TITLE": "Fokuszeiten",
            "SETTINGS_SECTION_DURATIONS_SUBTITLE": "Passe Fokus- und Pausenlängen an",
            "SETTINGS_SECTION_GOALS_TITLE": "Ziele",
            "SETTINGS_SECTION_GOALS_SUBTITLE": "Optimiere deinen Tagesplan",
            "SETTINGS_SECTION_ALERTS_TITLE": "Benachrichtigungen",
            "SETTINGS_SECTION_ALERTS_SUBTITLE": "Passe dein Pomodoro-Erlebnis an",
            "SETTINGS_SECTION_SOUND_TITLE": "Timer-Sound",
            "SETTINGS_SECTION_SOUND_SUBTITLE": "Wähle und steuere den Tick-Tack-Rhythmus",
            "SETTINGS_SECTION_LANGUAGE_TITLE": "App-Sprache",
            "SETTINGS_SECTION_LANGUAGE_SUBTITLE": "In welcher Sprache soll Simpo sprechen?",
            "SETTINGS_SECTION_THEME_TITLE": "Design",
            "SETTINGS_SECTION_THEME_SUBTITLE": "Wähle das App-Aussehen",
            "THEME_SYSTEM": "Systemstandard",
            "THEME_GRADIENT": "Farbverlauf",
            "THEME_OLEDDARK": "OLED Dunkel",
            "THEME_LIGHT": "Hell",
            "SETTINGS_SECTION_CREATOR_TITLE": "Entwickler",
            "SETTINGS_SECTION_CREATOR_SUBTITLE": "Melde dich und lass uns Simpo gemeinsam verbessern",
            "SETTINGS_CREATOR_LINKEDIN": "LinkedIn",
            "SETTINGS_CREATOR_X": "X",
            "SETTINGS_CREATOR_EMAIL": "E-Mail",
            "SETTINGS_CREATOR_EMAIL_SUBJECT": "Simpo Feedback",
            "FOCUS_BACKGROUND_REFRESH_TITLE": "Hintergrundaktualisierung deaktiviert",
            "FOCUS_BACKGROUND_REFRESH_MESSAGE": "Damit Simpo Fokus-Benachrichtigungen rechtzeitig senden kann, aktiviere in Einstellungen > Allgemein > Hintergrundaktualisierung die Freigabe für Simpo.",
            "FOCUS_BACKGROUND_REFRESH_BUTTON": "Einstellungen öffnen",
            "SETTINGS_LANGUAGE_NOTE": "Diese Wahl richtet sich nach deiner Gerätesprache. Du kannst sie jederzeit ändern.",
            "SETTINGS_DURATION_FORMAT": "%d Min",
            "FOCUS_PHASE_LABEL": "%@",
            "FOCUS_PHASE_PROGRESS": "Fortschritt",
            "PHASE_FOCUS_LABEL": "Fokus",
            "PHASE_SHORT_LABEL": "Kurze Pause",
            "PHASE_LONG_LABEL": "Lange Pause",
            "PHASE_IDLE_LABEL": "Bereit",
            "TIMER_PHASE_FOCUS": "Fokus",
            "TIMER_PHASE_SHORT": "Kurze Pause",
            "TIMER_PHASE_LONG": "Lange Pause",
            "TIMER_PHASE_IDLE": "Bereit",
            "SETTINGS_STEPPER_DAILY": "Tägliches Pomodoro-Ziel",
            "SETTINGS_STEPPER_LONG": "Fokus-Sessions vor einer langen Pause",
            "SETTINGS_TARGET_TITLE_DAILY": "Tagesziel",
            "SETTINGS_TARGET_TITLE_LONG": "Lange-Pause-Zähler",
            "SETTINGS_UNIT_POMODORO": "Pomodoros",
            "SETTINGS_UNIT_FOCUS": "Fokus",
            "SETTINGS_TARGET_LABEL": "Ziel: %d %@",
            "SETTINGS_TOGGLE_SOUND_TITLE": "Tonalarme",
            "SETTINGS_TOGGLE_SOUND_DESC": "Ton bei Phasenwechsel abspielen",
            "SETTINGS_TOGGLE_HAPTIC_TITLE": "Haptisches Feedback",
            "SETTINGS_TOGGLE_HAPTIC_DESC": "Vibrieren bei Fokusende",
            "SETTINGS_TOGGLE_AUTO_TITLE": "Pausen automatisch starten",
            "SETTINGS_TOGGLE_AUTO_DESC": "Nach Fokusende Pause automatisch starten",
            "SETTINGS_TOGGLE_NOTIF_TITLE": "Lokale Benachrichtigungen",
            "SETTINGS_TOGGLE_NOTIF_DESC": "Benachrichtigungen senden, wenn die App im Hintergrund ist",
            "SETTINGS_TOGGLE_TICK_TITLE": "Tick-Tack-Sound",
            "SETTINGS_TOGGLE_TICK_DESC": "Tick-Tack während des Fokus abspielen",
            "SETTINGS_TOGGLE_OVERRIDE_TITLE": "Stummmodus ignorieren",
            "SETTINGS_TOGGLE_OVERRIDE_DESC": "Ton auch bei Stummschaltung abspielen",
            "SETTINGS_PICKER_TICK": "Sound",
            "TICK_SOUND_classic": "Klassisch",
            "TICK_SOUND_wood": "Holz",
            "TICK_SOUND_digital": "Digital",
            "TICK_SOUND_loFi": "Lo-Fi",
            "TICK_SOUND_glass": "Glas",
            "SETTINGS_BUTTON_PREVIEW": "Sound anhören",
            "SETTINGS_VOLUME_LABEL": "Lautstärke",
            "SETTINGS_PERCENT_FORMAT": "%d%%",
            "SETTINGS_STEPPER_VALUE_SESSIONS": "%d Sitzungen",
            "SETTINGS_BUTTON_CANCEL": "Abbrechen",
            "SETTINGS_BUTTON_SAVE": "Speichern",
            "SETTINGS_LANGUAGE_PICKER": "Sprache",
            "BUY_MARKET_CAP": "Marktkapitalisierung",
            "BUY_AMOUNT_LABEL": "Betrag",
            "BUY_TOTAL_TITLE": "Kaufsumme",
            "BUY_CONFIRM": "Kaufen",
            "BUY_CLOSE": "Schließen",
            "BUY_CONFIRM_SUCCESS": "Du hast %@ im Wert von %@ gekauft.",
            "BUY_INSUFFICIENT": "Unzureichendes Guthaben",
            "BUY_QUICK_AMOUNT": "Schnellbetrag",
            "BUY_AMOUNT_TRY": "%@ TRY",
            "BUY_AMOUNT_TOKEN": "%@ %@",
            "BUY_STATS_HELD": "Bestand",
            "BUY_STATS_AVERAGE": "Durchschnitt",
            "BUY_STATS_MARKET": "Markt",
            "ONBOARD_STEP_WELCOME": "Willkommen bei Simpo",
            "ONBOARD_STEP_THEME": "Design wählen",
            "ONBOARD_STEP_FOCUS": "Fokusrhythmus wählen",
            "ONBOARD_STEP_BREAKS": "Pausen festlegen",
            "ONBOARD_STEP_FINANCE": "Verdienst & Zinsen verstehen",
            "ONBOARD_STEP_HOME": "Zuhause gestalten",
            "ONBOARD_STEP_NOTIFICATIONS": "Benachrichtigungen aktivieren",
            "ONBOARD_STEP_PROFILE": "Erzähl uns von dir",
            "ONBOARD_SUB_WELCOME": "Verwalte deine Fokuszeit mit Simpo. Lass es uns in ein paar Schritten personalisieren.",
            "ONBOARD_SUB_THEME": "Wähle das App-Design. Du kannst es jederzeit ändern.",
            "ONBOARD_SUB_FOCUS": "Passe Fokusdauer und Tagesziele nach Bedarf an.",
            "ONBOARD_SUB_BREAKS": "Wähle Dauer und Automatikstart für kurze und lange Pausen.",
            "ONBOARD_SUB_FINANCE": "Erfahre, wie du Coins verdienst und ausgibst.",
            "ONBOARD_SUB_HOME": "Im Zuhause-Tab warten Dekor und Themen.",
            "ONBOARD_SUB_NOTIFICATIONS": "Soll Simpo dich bei Fokus-/Pausenende informieren?",
            "ONBOARD_SUB_PROFILE": "Letzter Schritt: Wie sollen wir dich nennen?",
            "ONBOARD_PRIMARY_NEXT": "Weiter",
            "ONBOARD_PRIMARY_START": "Start",
            "ONBOARD_BACK": "Zurück",
            "ONBOARD_NAME_PROMPT": "Wie heißt du?",
            "ONBOARD_NAME_HINT": "Du kannst diese Einstellungen später im Menü ändern.",
            "ONBOARD_LANGUAGE_TITLE": "Sprache wählen",
            "ONBOARD_LANGUAGE_DESCRIPTION": "In welcher Sprache möchtest du Simpo nutzen? (Standard: Gerätesprache)",
            "ONBOARD_LANGUAGE_NOTE": "Du kannst die Sprache später in den Einstellungen ändern.",
            "ONBOARD_FOCUS_DURATION": "Fokusdauer: %d Min",
            "ONBOARD_DAILY_TARGET": "Tagesziel",
            "ONBOARD_DAILY_TARGET_VALUE": "%d Pomodoros",
            "ONBOARD_SHORT_BREAK": "Kurze Pause: %d Min",
            "ONBOARD_LONG_BREAK": "Lange Pause: %d Min",
            "ONBOARD_BEFORE_LONG_BREAK": "%d Fokus-Sessions vor langer Pause",
            "ONBOARD_AUTO_BREAKS": "Pausen automatisch starten",
            "ONBOARD_NOTIFICATIONS_TOGGLE": "Lokale Benachrichtigungen aktivieren",
            "ONBOARD_NOTIFICATIONS_DESC": "Erhalte Hinweise bei Fokus- oder Pausenende. Später im Menü anpassbar.",
            "ONBOARD_FINANCE_EARN": "Coins mit Pomodoros verdienen",
            "ONBOARD_FINANCE_EARN_DESC": "Jede fokussierte Minute bringt dir Coins zum Investieren oder Ausgeben.",
            "ONBOARD_FINANCE_BANK": "Mit Zinsen wachsen",
            "ONBOARD_FINANCE_BANK_DESC": "Lege Coins im Bank-Tab an, verfolge die Zinsen und sammle Erträge.",
            "ONBOARD_FINANCE_MARKET": "Im Markt ausgeben",
            "ONBOARD_FINANCE_MARKET_DESC": "Kaufe Coins oder Deko für dein Zuhause.",
            "ONBOARD_HOME_CUSTOMIZE": "Zuhause personalisieren",
            "ONBOARD_HOME_CUSTOMIZE_DESC": "Nutze Coins für Dekor und verwalte dein Inventar.",
            "ONBOARD_HOME_THEMES": "Themen & Boni",
            "ONBOARD_HOME_THEMES_DESC": "Wechsle Themen, um dein Umfeld zu erneuern und Boni zu erhalten.",
            "ONBOARD_WELCOME_DESC": "Simpo macht dich fit für einen produktiven Tag. Lass uns ein paar Einstellungen wählen.",
            "STATS_TOTAL_FOCUS_TIME": "Gesamte Fokuszeit",
            "STATS_TOTAL_SESSIONS": "Gesamte Sessions",
            "STATS_ACTIVE_DAYS": "Aktive Tage",
            "STATS_AVERAGE_SESSION": "Durchschnitt",
            "STATS_PERFORMANCE_SUMMARY": "Leistungsübersicht",
            "STATS_BEST_STREAK": "Längste Serie",
            "STATS_STREAK_VALUE": "x%1$d Sessions",
            "STATS_DAILY_AVERAGE": "Täglicher Durchschnitt",
            "STATS_LAST_FOCUS": "Letzter Fokus",
            "STATS_LAST_FOCUS_NONE": "Noch nicht",
            "STATS_DAILY_GOAL": "Tagesziel",
            "STATS_GOAL_COMPLETE": "Tagesziel erreicht!",
            "STATS_GOAL_PROGRESS": "Fast geschafft, bleib dran.",
            "STATS_ACTIVITY_CALENDAR": "Aktivitätskalender",
            "STATS_ACTIVITY_DAYS": "Letzte %1$d Tage",
            "STATS_HOURS_FORMAT": "%1$d Std %2$d Min",
            "STATS_MINUTES_FORMAT": "%1$d Min",
            "STATS_GOAL_VALUE": "%1$d/%2$d",
            "Dili Ayarla": "Sprache ändern",
            "Uygulama dilini seç": "App-Sprache auswählen",
            "Bu tercih cihaz diline göre otomatik seçilir. Ayarlardan her zaman değiştirebilirsin.": "Wird standardmäßig aus der System-Sprache übernommen. Du kannst es jederzeit ändern.",
            "Simpo'ya Hoş Geldin": "Willkommen bei Simpo",
            "Odak süreni Simpo ile yönet. Birkaç adımda kişiselleştirelim.": "Verwalte deine Fokuszeit mit Simpo. Lass es uns in ein paar Schritten personalisieren.",
            "Odak Ritmini Seç": "Wähle deinen Fokusrhythmus",
            "Odak ve günlük hedef ayarlarını kendine göre yap.": "Passe Fokuszeiten und Tagesziele an.",
            "Mola Tercihlerini Belirle": "Lege deine Pausen fest",
            "Kısa ve uzun mola sürelerini, otomatik başlatmayı seç.": "Wähle kurze und lange Pausen sowie den Automatikstart.",
            "Kazanç und Faiz Mantik": "Verdienst & Zinsen",
            "Kazancını nasıl artıracağını und wo du sie ausgeben kannst.": "Erfahre, wie du Coins verdienst und wo du sie ausgeben kannst.",
            "Evini Kişiselleştir": "Gestalte dein Zuhause",
            "Ev sekmesinde dekorasyon und Themen warten im Zuhause-Tab auf dich.": "Dekor und Themen warten im Zuhause-Tab auf dich.",
            "Bildirimleri Açalım": "Benachrichtigungen aktivieren",
            "Odak und Pausenende benachrichtigt werden?": "Möchtest du bei Fokus- oder Pausenende benachrichtigt werden?",
            "Seni Tanıyalım": "Erzähl uns von dir",
            "Son adım: seni nasıl çağıralım?": "Letzter Schritt: Wie sollen wir dich nennen?",
            "Focus Forest macht dich fit für einen produktiven Tag. Lass uns ein paar Einstellungen wählen.": "Focus Forest macht dich fit für einen produktiven Tag. Lass uns ein paar Einstellungen wählen.",
            "Günlük hedef": "Tagesziel",
            "Uzun moladan önce %d odak": "Lange Pause nach %d Fokus-Sessions",
            "Pausen automatisch starten": "Pausen automatisch starten",
            "Yerel bildirimleri aç": "Lokale Benachrichtigungen aktivieren",
            "Diese Einstellungen kannst du jederzeit im Menü ändern.": "Diese Einstellungen kannst du jederzeit im Menü ändern.",
            "Başla": "Los geht's",
            "İleri": "Weiter",
            "Merhaba, %@ 👋": "Hallo, %@ 👋",
            "Gestalte dein Zuhause, kaufe Deko mit Coins und personalisiere deinen Arbeitsplatz.": "Gestalte dein Zuhause, kaufe Deko mit Coins und personalisiere deinen Arbeitsplatz.",
            "Zuhause-Markt": "Zuhause-Markt",
            "Entdecke neue Deko mit deinen Coins.": "Entdecke neue Deko mit deinen Coins.",
            "Dein Wohnbereich": "Dein Wohnbereich",
            "Ordne platzierte Gegenstände sofort.": "Ordne platzierte Gegenstände sofort.",
            "Noch keine Gegenstände platziert. Kaufe etwas im Zuhause-Markt.": "Noch keine Gegenstände platziert. Kaufe etwas im Zuhause-Markt.",
            "Vermögenswerte": "Vermögenswerte",
            "Du hast noch nicht investiert": "Du hast noch nicht investiert",
            "Verkaufen": "Verkaufen",
            "Geldbörse": "Geldbörse",
            "Passive Einnahmen": "Passive Einnahmen",
            "Noch keine Transaktionen": "Noch keine Transaktionen",
            "Transaktionen": "Transaktionen",
            "In Zinsen anlegen": "In Zinsen anlegen",
            "Von Zinsen abheben": "Von Zinsen abheben",
            "Anlegen": "Anlegen",
            "Abheben": "Abheben",
            "Ungültiger Anlagebetrag": "Ungültiger Anlagebetrag",
            "Nicht genug Guthaben (Verfügbar: %@)": "Nicht genug Guthaben (Verfügbar: %@)",
            "₺%.2f in Zinsen angelegt": "₺%.2f in Zinsen angelegt",
            "Transaktion fehlgeschlagen": "Transaktion fehlgeschlagen",
            "Ungültiger Abhebebetrag": "Ungültiger Abhebebetrag",
            "Es kann nicht mehr als der gesperrte Betrag abgehoben werden (Gesperrt: %@)": "Es kann nicht mehr als der gesperrte Betrag abgehoben werden (Gesperrt: %@)",
            "₺%.2f abgehoben": "₺%.2f abgehoben",
            "Bankkonto": "Bankkonto",
            "Verfügbar": "Verfügbar",
            "Gesperrt (Zinsen)": "Gesperrt (Zinsen)",
            "Gesamteinnahmen": "Gesamteinnahmen",
            "Jahreszins": "Jahreszins",
            "Tageszins": "Tageszins",
            "HOME_GUEST_NAME": "Simpo Freund",
            "HOME_GREETING": "Hallo, %@",
            "HOME_SUBTITLE": "Willkommen zurück in deinem Simpo-Zuhause. Personalisiere den Raum und steigere deine Motivation.",
            "HOME_BUTTON_INVENTORY": "Inventar",
            "HOME_BALANCE_PRIMARY": "Geldbörse",
            "HOME_BALANCE_STAKED": "Angelegt",
            "HOME_SEGMENT_OVERVIEW": "Übersicht",
            "HOME_SEGMENT_STUDIO": "Zuhause",
            "HOME_SEGMENT_MARKET": "Markt",
            "HOME_ACTIVE_THEME_TITLE": "Aktives Thema",
            "HOME_ACTIVE_THEME_LABEL": "Themenatmosphäre",
            "HOME_ACTIVE_THEME_BUTTON": "Deko",
            "HOME_STATS_TITLE": "Fokus-Statistiken",
            "HOME_STATS_SUBTITLE": "Du näherst dich deinem Tagesziel",
            "HOME_STATS_COMPLETED": "Abgeschlossen",
            "HOME_STATS_SPENT": "Ausgegeben",
            "HOME_STATS_PASSIVE": "Passiv",
            "HOME_THEME_BONUS": "%d%% Energiebonus",
            "HOME_STUDIO_TITLE": "Dein Bereich",
            "HOME_STUDIO_SUBTITLE": "Platziere Gegenstände sofort neu.",
            "HOME_STUDIO_BUTTON": "Inventar",
            "HOME_STUDIO_EMPTY": "Noch keine Gegenstände platziert. Schau im Zuhause-Markt vorbei.",
            "HOME_MARKET_TITLE": "Zuhause-Markt",
            "HOME_MARKET_SUBTITLE": "Entdecke neue Dekoration mit deinen Coins.",
            "HOME_MARKET_PURCHASED": "Im Besitz",
            "HOME_DECOR_REMOVE": "Entfernen",
            "HOME_MARKET_SECTION_GENERIC": "%@",
            "HOME_MARKET_SECTION_STARTER": "Starter Pack",
            "HOME_MARKET_SECTION_WORKSHOP": "Workspace",
            "HOME_MARKET_SECTION_RELAX": "Relax Corner",
            "HOME_MARKET_SECTION_COLLECTION": "Collection",
            "NOTIF_FOCUS_DONE_TITLE": "Fokus beendet",
            "NOTIF_FOCUS_DONE_BODY": "Stark! Gönn dir jetzt eine verdiente Pause.",
            "NOTIF_BREAK_DONE_TITLE": "Pause vorbei",
            "NOTIF_BREAK_DONE_BODY": "Simpo ist bereit – lass uns wieder loslegen!",
            "ROOM_THEME_STARTER": "Starterhain",
            "ROOM_THEME_LAKE": "Seevilla",
            "ROOM_ASSET_WOOD_DESK": "Holzschreibtisch",
            "ROOM_DESC_WOOD_DESK": "Ein großzügiger, minimalistischer Arbeitsplatz.",
            "ROOM_ASSET_FOCUS_TIMER": "FocusSand-Timer",
            "ROOM_DESC_FOCUS_TIMER": "Verfolge deine Sitzungen mit einer Sanduhr.",
            "ROOM_ASSET_ERGO_CHAIR": "Ergonomischer Stuhl",
            "ROOM_DESC_ERGO_CHAIR": "Komfort für langes, fokussiertes Arbeiten.",
            "ROOM_ASSET_MEDITATION_MAT": "Meditationsmatte",
            "ROOM_DESC_MEDITATION_MAT": "Nutze kurze Pausen für Achtsamkeit.",
            "ROOM_ASSET_SILENT_PLANT": "Stille Pflanze",
            "ROOM_DESC_SILENT_PLANT": "Eine beruhigende Monstera, die den Raum belebt.",
            "ROOM_ASSET_VINTAGE_LAMP": "Vintage-Lampe",
            "ROOM_DESC_VINTAGE_LAMP": "Warmweißes Licht für Abendsessions.",
            "ROOM_ASSET_RETRO_CONSOLE": "Retro-Konsole",
            "ROOM_DESC_RETRO_CONSOLE": "Spiel in Pausen ein entspanntes Game.",
            "ROOM_ASSET_VINYL_PLAYER": "Vinylspieler",
            "ROOM_DESC_VINYL_PLAYER": "Spiele deine Lo-Fi-Playlist stilvoll ab.",
            "ROOM_ASSET_MINI_LIBRARY": "Mini-Bibliothek",
            "ROOM_DESC_MINI_LIBRARY": "Präsentiere deine Lieblingsbücher.",
            "ROOM_ASSET_MINI_PLANT": "Mini-Pflanze",
            "ROOM_DESC_MINI_PLANT": "Bringt sofort Farbe ins Zimmer.",
            "ROOM_ASSET_BAMBOO_DESK": "Bambusschreibtisch",
            "ROOM_DESC_BAMBOO_DESK": "Minimalistischer Schreibtisch aus Bambus.",
            "ROOM_ASSET_ZEN_PLANT": "Zen-Pflanze",
            "ROOM_DESC_ZEN_PLANT": "Verleiht ruhige, fokussierte Energie.",
            "ROOM_ASSET_WARM_LIGHT": "Sanftes Licht",
            "ROOM_DESC_WARM_LIGHT": "Weiche Beleuchtung für Gemütlichkeit.",
            "ROOM_ASSET_LAKE_VIEW": "Seeblick",
            "ROOM_DESC_LAKE_VIEW": "Blicke auf eine stille Seenlandschaft.",
            "ROOM_ASSET_HAMMOCK": "Hängematte",
            "ROOM_DESC_HAMMOCK": "Ideal für erholsame Pausen.",
            "ROOM_ASSET_WOOD_SHELF": "Holzregal",
            "ROOM_DESC_WOOD_SHELF": "Bewahre Bücher stets griffbereit auf.",
            "HOME_PURCHASE_PLACE": "Platzieren",
            "HOME_PURCHASE_BUY_PLACE": "Kaufen & platzieren",
            "HOME_PURCHASE_PLACED": "%@ wurde in deinem Zuhause platziert",
            "HOME_PURCHASE_PURCHASED": "%@ gekauft und platziert",
            "HOME_PURCHASE_BALANCE_ERROR": "Nicht genug Guthaben. Verdiene weitere Coins.",
            "HOME_OWNED_EMPTY": "Du hast noch keine Gegenstände gekauft.",
            "HOME_NAV_CLOSE": "Schließen",
            "SETTINGS_SECTION_BACKGROUND_TITLE": "Background Refresh",
            "SETTINGS_SECTION_BACKGROUND_SUBTITLE": "Keep it on so focus alerts arrive on time",
            "SETTINGS_BACKGROUND_READY_TITLE": "Notifications ready",
            "SETTINGS_BACKGROUND_ALERT_TITLE": "Background refresh disabled",
            "SETTINGS_BACKGROUND_ENABLE_NOTIF": "Allow notification permission so Simpo can alert you when sessions finish.",
            "SETTINGS_BACKGROUND_ENABLE_REFRESH": "Enable Background App Refresh for Simpo under Settings > General so alerts aren't delayed.",
            "SETTINGS_BACKGROUND_ALL_GOOD": "Background refresh and notification permissions are active. Simpo is all set!",
            "SETTINGS_BACKGROUND_ALLOW_NOTIF": "Request notification access",
            "SETTINGS_BACKGROUND_OPEN_SETTINGS": "Open Simpo settings",
            "TXN_REWARD_POMODORO": "Pomodoro-Belohnung",
            "TXN_INTEREST_GAIN": "Zinsen erhalten",
            "TXN_STAKE_DEPOSIT": "Eingezahlt auf Zinsen",
            "TXN_STAKE_WITHDRAW": "Abgehoben von Zinsen",
            "TXN_THEME_UNLOCK": "%@ Theme freigeschaltet",
            "TXN_MARKET_BUY": "%@ gekauft",
            "TXN_MARKET_SELL": "%@ verkauft",
            "CATEGORY_UNTAGGED": "Ohne Tag",
            "CATEGORY_CODING": "Programmierung",
            "CATEGORY_ALGORITHMS": "Algorithmen",
            "CATEGORY_PHYSICS": "Physik",
            "CATEGORY_BUSINESS": "Business",
            "CATEGORY_MISC": "Sonstiges",
            "CATEGORY_TITLE": "Kategorie",
            "CATEGORY_PICKER_TITLE": "Kategorie wählen",
            "CATEGORY_PICKER_SUBTITLE": "Wähle eine Kategorie für diese Fokus-Session",
            "ANALYTICS_TITLE": "Jahresanalyse",
            "ANALYTICS_TODAY": "Heute",
            "ANALYTICS_WEEK": "Diese Woche",
            "ANALYTICS_MONTH": "Dieser Monat",
            "ANALYTICS_YEAR": "Dieses Jahr",
            "ANALYTICS_ALL_TIME": "Gesamt",
            "ANALYTICS_CATEGORY_BREAKDOWN": "Kategorie-Aufschlüsselung",
            "ANALYTICS_BEST_RECORDS": "Beste Aufzeichnungen",
            "ANALYTICS_BEST_DAY": "Bester Tag",
            "ANALYTICS_BEST_WEEK": "Beste Woche",
            "ANALYTICS_BEST_MONTH": "Bester Monat",
            "ANALYTICS_BEST_STREAK": "Beste Serie",
            "ANALYTICS_ACTIVITY_CALENDAR": "Aktivitätskalender",
            "ANALYTICS_NO_DATA": "Noch keine Daten",
            "ANALYTICS_DAYS": "Tage",
            "ANALYTICS_CONSECUTIVE": "aufeinanderfolgend",
            "ANALYTICS_SESSIONS_COUNT": "%d Sitzungen",
            "ANALYTICS_FOCUS_TIME": "Fokuszeit",
            "ANALYTICS_SESSION": "Sitzung",
            "ANALYTICS_SESSIONS": "Sitzungen",
            "CATEGORY_PREDEFINED": "Vordefiniert",
            "CATEGORY_CUSTOM": "Benutzerdefinierte Kategorien",
            "ADD_CATEGORY_TITLE": "Neue Kategorie",
            "ADD_CATEGORY_SUBTITLE": "Erstelle deine eigene Kategorie",
            "CATEGORY_NAME": "Kategoriename",
            "CATEGORY_NAME_PLACEHOLDER": "Kategoriename eingeben",
            "CATEGORY_ICON": "Symbol",
            "CATEGORY_COLOR": "Farbe",
            "CATEGORY_PREVIEW": "Vorschau",
            "CANCEL": "Abbrechen",
            "SAVE": "Speichern",
            "SEARCH_CATEGORIES": "Kategorien durchsuchen...",
            "NO_CUSTOM_CATEGORIES": "Noch keine benutzerdefinierten Kategorien",
            "NO_CUSTOM_CATEGORIES_SUBTITLE": "Erstelle deine erste benutzerdefinierte Kategorie und organisiere deine Fokussitzungen",
            "CREATE_FIRST_CATEGORY": "Erste Kategorie erstellen",
            "PAYWALL_TITLE": "SimpoFocus Pro",
            "PAYWALL_SUBTITLE": "Schalte alle Premium-Funktionen frei und hebe dein Fokus-Erlebnis auf ein neues Level.",
            "PAYWALL_FEATURE_CATEGORIES": "Unbegrenzte benutzerdefinierte Kategorien",
            "PAYWALL_FEATURE_ANALYTICS": "Erweiterte Analysen & Heatmap",
            "PAYWALL_FEATURE_THEMES": "Alle Themen und Raumdekorationen",
            "PAYWALL_FEATURE_TIMER": "Erweiterte Timer-Einstellungen",
            "PAYWALL_FEATURE_COINS": "2x Coin-Verdienstmultiplikator",
            "PAYWALL_PLAN_WEEKLY": "Wöchentlich",
            "PAYWALL_PLAN_MONTHLY": "Monatlich",
            "PAYWALL_PLAN_YEARLY": "Jährlich",
            "PAYWALL_PERIOD_WEEK": "Woche",
            "PAYWALL_PERIOD_MONTH": "Monat",
            "PAYWALL_PERIOD_YEAR": "Jahr",
            "PAYWALL_BEST_VALUE": "Bester Wert",
            "PAYWALL_SUBSCRIBE": "Abonnieren",
            "PAYWALL_ALREADY_PRO": "Bereits Pro",
            "PAYWALL_RESTORE": "Käufe wiederherstellen",
            "PAYWALL_TERMS": "Das Abonnement verlängert sich automatisch je nach gewähltem Plan. Du kannst jederzeit in den App Store-Einstellungen kündigen.",
            "SPECIAL_OFFER_WAIT": "Warte!",
            "SPECIAL_OFFER_TITLE": "Sonderangebot nur für dich!",
            "SPECIAL_OFFER_SUBTITLE": "90% Rabatt für begrenzte Zeit",
            "SPECIAL_OFFER_ORIGINAL_PRICE": "Regulärer Preis",
            "SPECIAL_OFFER_NOW": "Jetzt",
            "SPECIAL_OFFER_DISCOUNT_BADGE": "90% RABATT",
            "SPECIAL_OFFER_TIMER_LABEL": "Angebot läuft ab in",
            "SPECIAL_OFFER_CTA": "Angebot sichern",
            "SPECIAL_OFFER_NO_THANKS": "Nein danke, vielleicht später",
            "SPECIAL_OFFER_PER_WEEK": "/Woche",
            "ROOM_HEADER_TITLE": "Raum-Themen",
            "ROOM_HEADER_DESC": "Entdecke Themen, schalte neue Atmosphären frei und gestalte deinen Raum nach deiner Motivation.",
            "ROOM_ACTIVE_THEME": "AKTIVES THEMA",
            "ROOM_THEME_EFFECT": "Thema-Fokus-Boost: +%d%%",
            "ROOM_CHOOSE_THEME": "Thema wählen",
            "ROOM_UNLOCK_HINT": "Wenn du neue Themen freischaltest, erscheinen mehr Dekorationsoptionen im Home-Tab.",
            "THEME_PRICE_COINS": "%d Coins",
            "SELL_COIN_QUANTITY_UNIT": "Stück",
            "COIN_STORE_TITLE": "Coin-Shop",
            "COIN_STORE_BALANCE": "Aktuelles Guthaben",
            "COIN_STORE_SUCCESS_TITLE": "Kauf erfolgreich",
            "COIN_STORE_SUCCESS_MSG": "%d Coins wurden deinem Konto gutgeschrieben!",
            "COIN_STORE_OK": "OK",
            "PRO_BADGE": "Pro",
            "PRO_GATE_ANALYTICS": "Erweiterte Analysen mit Pro freigeschaltet",
            "PRO_GATE_ANALYTICS_DESC": "Jahres-Heatmap, Kategorie-Aufschlüsselung und beste Aufzeichnungen anzeigen.",
            "PRO_GATE_UNLOCK": "Auf Pro upgraden",
            "PRO_BANNER_TITLE": "2x Münz-Multiplikator",
            "PRO_BANNER_SUBTITLE": "Mit Pro freischalten",
            "PRO_COINSTORE_BANNER": "Alle Münzen 2x mit Pro!",
            "PRO_COINSTORE_CTA": "Pro holen",
            "PRO_SESSION_NUDGE": "Verdiene 2x Münzen mit Pro",
            "ADD_CATEGORY_LIMIT": "%d/%d benutzerdefinierte Kategorien (unbegrenzt mit Pro)",
            "THEME_PICKER_TITLE": "Thema wählen",
            "SETTINGS_DURATIONS_PRO_HINT": "Zeiten mit Pro anpassen",
            "TXN_COIN_PACK_PURCHASED": "Coin-Paket gekauft"
        ]
    ]
}
